import { describe, expect, it } from 'vitest'
import { decideAdjustment, emptyState, initializeProject, nextAction, proposeAdjustment, recordEvidence, setTaskState } from '../src/domain.js'

function project() { return initializeProject(emptyState(), { goal: '掌握商业级 Agent 系统', experience: '5 年开发，做过 RAG', weeklyHours: 10, idempotencyKey: 'init-1' }) }
describe('LearnLoop domain', () => {
  it('publishes exactly one active immutable plan', () => { const state = project(); expect(state.plans.filter(p => p.status === 'active')).toHaveLength(1); const adjusted = proposeAdjustment(state, { impact: 'minor', reason: '提前薄弱点练习', diff: ['+ 影响等级练习'], idempotencyKey: 'minor-1' }); expect(adjusted.plans).toHaveLength(2); expect(adjusted.plans.filter(p => p.status === 'active')).toHaveLength(1); expect(state.plans[0]?.status).toBe('active') })
  it('does not apply a major adjustment without approval', () => { const state = proposeAdjustment(project(), { impact: 'major', reason: '每周投入减半', diff: ['10h → 5h', '里程碑 +3 周'], idempotencyKey: 'major-1' }); expect(state.adjustments[0]?.state).toBe('proposed'); expect(state.plans).toHaveLength(1); const applied = decideAdjustment(state, state.adjustments[0]!.id, 'apply'); expect(applied.plans).toHaveLength(2); expect(applied.adjustments[0]?.state).toBe('applied') })
  it('deduplicates state writes by idempotency key', () => { const once = recordEvidence(project(), { idempotencyKey: 'ev-1', conceptId: 'runtime-state', kind: 'explanation', summary: 'finish 是全局结束，status 是可恢复状态', source: { sessionId: 's1', messageRange: 'm1-m2' }, confidence: .8 }); expect(recordEvidence(once, { ...once.evidence[0]!, idempotencyKey: 'ev-1' }).evidence).toHaveLength(1) })
  it('requires diverse evidence before mastery', () => { let state = project(); state = recordEvidence(state, { idempotencyKey: 'a', conceptId: 'runtime-state', kind: 'explanation', summary: '解释', source: { sessionId: 's', messageRange: '1' }, confidence: .8 }); expect(state.mastery[0]?.level).toBe('practicing'); state = recordEvidence(state, { idempotencyKey: 'b', conceptId: 'runtime-state', kind: 'pseudocode', summary: '伪代码', source: { sessionId: 's', messageRange: '2' }, confidence: .9 }); expect(state.mastery[0]?.level).toBe('demonstrated'); state = recordEvidence(state, { idempotencyKey: 'c', conceptId: 'runtime-state', kind: 'assessment', summary: '闭卷评测', source: { sessionId: 's', messageRange: '3' }, confidence: .9 }); expect(state.mastery[0]?.level).toBe('mastered') })
  it('computes next action from authoritative plan state', () => { const state = project(); const task = nextAction(state)!; expect(task.status).toBe('active'); const complete = setTaskState(state, { taskId: task.id, status: 'completed', idempotencyKey: 'done-1' }); expect(nextAction(complete)?.title).toContain('Planner') })
})
