import {describe,expect,it} from 'vitest'
import {activeProject,beginWorkspaceOnboarding,compileProfileDraftFromInterview,confirmWorkspaceProfile,consumeProfileFallbackMessage,emptyState,encodeToolError,finalizeLearnLoopToolError,normalizeNativeAnswer,prepareProfileInterviewQuestion,probeDefinition,recordProfileInterviewAnswer,workspaceOf} from '../src/index.js'

const start=()=>beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'})
const answer=(state:ReturnType<typeof emptyState>,callId:string,selected:string[]=[],custom?:string,fallbackAfterSeq=10)=>{state=prepareProfileInterviewQuestion(state,{sessionId:'s',callId});const snapshot=activeProject(workspaceOf(state,'ws')).profileInterview.activeQuestion!;return recordProfileInterviewAnswer(state,{sessionId:'s',callId,questionId:snapshot.questionId,selected,custom,fallbackAfterSeq})}

describe('host-owned Profile interview transaction',()=>{
 it('maps real native labels and advances before returning',()=>{let state=start();state=answer(state,'kind',['掌握一项具体技能']);const interview=activeProject(workspaceOf(state,'ws')).profileInterview;expect(interview.probes['goal.kind'].normalizedValue).toBe('skill');expect(interview.currentProbeId).toBe('goal.subject');expect(interview.activeQuestion).toBeNull();expect(interview.topics.goal.status).toBe('collecting')})
 it.each([['current-foundation.level','初学者','beginner'],['time-budget.weekly-hours','2 小时',2],['learning-mode.mode','知识优先','knowledge-first'],['practice-capacity.capacity','暂不实践','none']] as const)('maps %s label %s to %s',(probeId,label,value)=>{const definition=probeDefinition(probeId);expect(normalizeNativeAnswer(definition,definition.options!,[label])).toEqual({valid:true,value,empty:false})})
 it('custom overrides selected and legitimate technical content is accepted',()=>{let state=start();state=answer(state,'kind',['掌握一项具体技能'],'学习 system prompt 和 tool call 的工程设计');expect(activeProject(workspaceOf(state,'ws')).profileInterview.probes['goal.kind'].normalizedValue).toBe('学习 system prompt 和 tool call 的工程设计')})
 it('rejects unknown and multiple labels without incrementing empty attempts',()=>{for(const selected of [['不存在'],['掌握一项具体技能','完成一个具体项目']]){let state=start();state=prepareProfileInterviewQuestion(state,{sessionId:'s',callId:'bad'});const before=activeProject(workspaceOf(state,'ws')).profileInterview.probes['goal.kind'].emptyAttempts,snapshot=activeProject(workspaceOf(state,'ws')).profileInterview.activeQuestion!;expect(()=>recordProfileInterviewAnswer(state,{sessionId:'s',callId:'bad',questionId:snapshot.questionId,selected})).toThrowError(expect.objectContaining({code:'INTERVIEW_QUESTION_CONTRACT_INVALID'}));expect(activeProject(workspaceOf(state,'ws')).profileInterview.probes['goal.kind'].emptyAttempts).toBe(before)}})
 it('enters fallback only after two true empty answers and consumes one new direct user message',()=>{let state=start();state=answer(state,'empty-one');let interview=activeProject(workspaceOf(state,'ws')).profileInterview;expect(interview.probes['goal.kind'].emptyAttempts).toBe(1);state=answer(state,'empty-two',[],undefined,20);interview=activeProject(workspaceOf(state,'ws')).profileInterview;expect(interview.awaitingChatProbeId).toBe('goal.kind');expect(interview.fallbackAfterSeq).toBe(20);expect(consumeProfileFallbackMessage(state,{sessionId:'s',messageId:'old',eventSeq:20,text:'掌握技能'})).toBe(state);state=consumeProfileFallbackMessage(state,{sessionId:'s',messageId:'user-1',eventSeq:21,text:'掌握一项具体技能'});interview=activeProject(workspaceOf(state,'ws')).profileInterview;expect(interview.probes['goal.kind'].normalizedValue).toBe('掌握一项具体技能');expect(interview.currentProbeId).toBe('goal.subject');expect(interview.awaitingChatProbeId).toBeNull();expect(interview.probes['goal.kind'].emptyAttempts).toBe(0);const replay=consumeProfileFallbackMessage(state,{sessionId:'s',messageId:'user-1',eventSeq:21,text:'掌握一项具体技能'});expect(replay).toBe(state);expect(interview.answers.filter(item=>item.messageId==='user-1')).toHaveLength(1)})
 it('replays a committed native answer after the Probe advanced',()=>{let state=start();state=answer(state,'kind',['掌握一项具体技能']);const revision=state.revision,count=activeProject(workspaceOf(state,'ws')).profileInterview.answers.length;const replay=recordProfileInterviewAnswer(state,{sessionId:'s',callId:'kind',questionId:'learnloop-profile-goal.kind',selected:['掌握一项具体技能']});expect(replay).toBe(state);expect(replay.revision).toBe(revision);expect(activeProject(workspaceOf(replay,'ws')).profileInterview.answers).toHaveLength(count)})
})

describe('deterministic Profile compiler',()=>{
 it('preserves example preference and all combined origins',()=>{let state=start();const project=activeProject(workspaceOf(state,'ws')),interview=project.profileInterview;interview.probes['learning-mode.example-preference'].normalizedValue='每个知识点都要有大量案例';interview.probes['learning-mode.example-preference'].answerIds=['examples'];interview.answers.push({id:'examples',probeId:'learning-mode.example-preference',topic:'learning-mode',source:'direct-user-message',sessionId:'s',questionId:null,questionCallId:null,selected:[],custom:'每个知识点都要有大量案例',messageId:'m',eventSeq:1,contentHash:'a'.repeat(64),status:'answered',createdAt:interview.createdAt});interview.probes['target-outcome.capability'].answerIds=['cap'];interview.probes['target-outcome.quality-bar'].answerIds=['quality'];for(const [id,probeId] of [['cap','target-outcome.capability'],['quality','target-outcome.quality-bar']] as const)interview.answers.push({id,probeId,topic:'target-outcome',source:'native-question',sessionId:'s',questionId:id,questionCallId:id,selected:[],custom:id,messageId:null,eventSeq:null,contentHash:null,status:'answered',createdAt:interview.createdAt});const profile=compileProfileDraftFromInterview(interview,{id:'p',revision:1,createdAt:interview.createdAt,updatedAt:interview.updatedAt});expect(profile.learningPreferences.exampleDensity).toBe('high');expect(profile.learningPreferences.additionalNotes).toContain('大量案例');expect(profile.fieldOrigins.targetOutcome).toEqual(expect.objectContaining({answerIds:['cap','quality']}));expect(profile.fieldOrigins.exampleDensity).toEqual(expect.objectContaining({answerIds:['examples']}))})
})

describe('V2 recovery and confirmation replay',()=>{
 it('renders final Interview errors with a complete recovery envelope',()=>{const rendered=finalizeLearnLoopToolError({} as never,{isError:true,error:{info:{code:'INTERVIEW_QUESTION_CONTRACT_INVALID'}}} as never)![0] as {type:'text';text:string};expect(rendered.text).toContain('LEARNLOOP_TOOL_ERROR_V2');expect(JSON.parse(rendered.text.match(/<learnloop-tool-error-json>\n(.*)\n<\/learnloop-tool-error-json>/s)![1]!)).toEqual(expect.objectContaining({version:2,recovery:{kind:'refresh-state',maxAttempts:0}}));expect(encodeToolError({code:'INTERVIEW_BATCH_NOT_ALLOWED',category:'conflict',message:'x',recovery:{kind:'refresh-state',maxAttempts:0}})).toContain('recovery')})
 it('replays confirmation after phase progression without another mutation',()=>{let state=start(),project=activeProject(workspaceOf(state,'ws'));project.phase='profile_review';project.profileInterview.status='drafted';project.profile={id:'p',revision:1,goal:'g',targetOutcome:'t',priorKnowledge:'p',experienceLevel:'beginner',knowledgeGaps:['g'],learningPreferences:{mode:'balanced',practiceCapacity:'light',explanationDepth:'standard',exampleDensity:'standard',additionalNotes:''},weeklyHours:2,constraints:[],successCriteria:['s'],unansweredQuestions:[],fieldOrigins:{},confirmedAt:null,createdAt:project.createdAt,updatedAt:project.updatedAt};project.profileRevision=1;const input={workspaceId:'ws',projectId:project.id,sessionId:'s',expectedRevision:1,profileRevision:1,idempotencyKey:'confirm'};state=confirmWorkspaceProfile(state,input);const revision=state.revision;expect(confirmWorkspaceProfile(state,input)).toBe(state);expect(state.revision).toBe(revision)})
})
