import {describe,expect,it} from 'vitest'
import {activeProject,beginWorkspaceOnboarding,createLearnLoopProfileQuestionTool,emptyState,workspaceOf,type LearnLoopState,type StateTable} from '../src/index.js'

class MemoryTable implements StateTable{constructor(private state:LearnLoopState){}get(){return this.state}async put(_id:string,value:LearnLoopState){this.state=value}async update(_id:string,update:(current:LearnLoopState)=>LearnLoopState){this.state=update(this.state);return this.state}}

describe('LearnLoop-owned native Profile question tool',()=>{
 it('sends Host labels through the real DSH seam and resolves only after persistence and progression',async()=>{const table=new MemoryTable(beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}));let observed:any;const native={ask:async(request:any)=>{observed=request;return{answers:[{id:request.questions[0].id,selected:['掌握一项具体技能']}]}}},sessions={tailSeq:()=>7} as any,tool=createLearnLoopProfileQuestionTool(table,native,sessions) as any;const result=await tool.execute({}, {agent:{id:'s'},callId:'native-1',signal:new AbortController().signal});expect(observed.questions).toEqual([expect.objectContaining({id:'learnloop-profile-goal.kind',options:expect.arrayContaining([expect.objectContaining({label:'掌握一项具体技能'})])})]);expect(result).toEqual({status:'answered',probeId:'goal.kind',nextProbeId:'goal.subject'});const interview=activeProject(workspaceOf(table.get('singleton')!,'ws')).profileInterview;expect(interview.probes['goal.kind'].normalizedValue).toBe('skill');expect(interview.currentProbeId).toBe('goal.subject');expect(interview.activeQuestion).toBeNull()})
 it('replays the canonical receipt without asking the provider again',async()=>{const table=new MemoryTable(beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}));let calls=0;const native={ask:async(request:any)=>{calls++;return{answers:[{id:request.questions[0].id,selected:['掌握一项具体技能']}]}}},tool=createLearnLoopProfileQuestionTool(table,native,{tailSeq:()=>2} as any) as any,exec={agent:{id:'s'},callId:'same',signal:new AbortController().signal};const first=await tool.execute({},exec),revision=table.get('singleton')!.revision;expect(await tool.execute({},exec)).toEqual(first);expect(calls).toBe(1);expect(table.get('singleton')!.revision).toBe(revision)})
 for(const failure of [{name:'ASK_ABORTED',error:Object.assign(new Error('aborted'),{code:'ASK_ABORTED'})},{name:'NO_PROVIDER',error:Object.assign(new Error('missing'),{code:'NO_PROVIDER'})},{name:'provider error',error:new Error('provider exploded')}])it(`releases activeQuestion after ${failure.name} without polluting attempts`,async()=>{const table=new MemoryTable(beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}));let calls=0;const tool=createLearnLoopProfileQuestionTool(table,{ask:async()=>{calls++;if(calls===1)throw failure.error;return{answers:[{id:'learnloop-profile-goal.kind',selected:['掌握一项具体技能']}]}}},{tailSeq:()=>2} as any) as any;await expect(tool.execute({},{agent:{id:'s'},callId:'failed',signal:new AbortController().signal})).rejects.toBe(failure.error);let interview=activeProject(workspaceOf(table.get('singleton')!,'ws')).profileInterview;expect(interview.activeQuestion).toBeNull();expect(interview.probes['goal.kind']).toMatchObject({emptyAttempts:0,invalidQuestionAttempts:0,normalizedValue:null});await expect(tool.execute({},{agent:{id:'s'},callId:'recovery',signal:new AbortController().signal})).resolves.toMatchObject({status:'answered'});interview=activeProject(workspaceOf(table.get('singleton')!,'ws')).profileInterview;expect(interview.currentProbeId).toBe('goal.subject')})
 for(const response of [{answers:[]},{answers:[{id:'wrong',selected:['掌握一项具体技能']}]},{answers:[{id:'learnloop-profile-goal.kind',selected:['不存在']}]},{answers:[{id:'learnloop-profile-goal.kind',selected:['掌握一项具体技能','完成一个具体项目']}]},{answers:[{id:'learnloop-profile-goal.kind',selected:[],custom:'学习 TypeScript'}]}])it('classifies native protocol errors separately from empty answers',async()=>{const table=new MemoryTable(beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}));const tool=createLearnLoopProfileQuestionTool(table,{ask:async()=>response},{tailSeq:()=>2} as any) as any;await expect(tool.execute({},{agent:{id:'s'},callId:'invalid',signal:new AbortController().signal})).rejects.toMatchObject({code:expect.stringMatching(/INTERVIEW_/) });const interview=activeProject(workspaceOf(table.get('singleton')!,'ws')).profileInterview;expect(interview.activeQuestion).toBeNull();expect(interview.probes['goal.kind']).toMatchObject({emptyAttempts:0,invalidQuestionAttempts:1,normalizedValue:null})})
})
