import {describe,expect,it} from 'vitest'
import {INTERVIEW_PROBES,activeProject,beginWorkspaceOnboarding,emptyState,normalizeNativeAnswer,prepareProfileInterviewQuestion,probeDefinition,recordProfileInterviewAnswer,workspaceOf} from '../src/index.js'
const start=()=>beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'})
const prepare=(state:ReturnType<typeof start>,callId:string,scaffoldOptions?:any[])=>prepareProfileInterviewQuestion(state,{sessionId:'s',callId,questionToken:activeProject(workspaceOf(state,'ws')).profileInterview.pendingQuestion!.token,scaffoldOptions})
describe('learner-first Profile interview',()=>{
 it('starts with free-text goal.subject and no goal.kind',()=>{const p=activeProject(workspaceOf(start(),'ws'));expect(p.profileInterview.currentProbeId).toBe('goal.subject');expect(INTERVIEW_PROBES.some(x=>String(x.id)==='goal.kind')).toBe(false);expect(probeDefinition('goal.subject').questionMode).toBe('free-text')})
 it('accepts native custom text and advances to scaffolded outcome with a different token',()=>{let s=start(),first=activeProject(workspaceOf(s,'ws')).profileInterview.pendingQuestion!.token;s=prepare(s,'c1');const q=activeProject(workspaceOf(s,'ws')).profileInterview.activeQuestion!;s=recordProfileInterviewAnswer(s,{sessionId:'s',callId:'c1',questionId:q.questionId,selected:[],custom:'简单了解量化交易系统'});const i=activeProject(workspaceOf(s,'ws')).profileInterview;expect(i.probes['goal.subject'].normalizedValue).toBe('简单了解量化交易系统');expect(i.currentProbeId).toBe('goal.outcome');expect(i.pendingQuestion!.token).not.toBe(first)})
 it('gives custom precedence over selected',()=>{const d=probeDefinition('current-foundation.level');expect(normalizeNativeAnswer(d,d.fixedOptions!,['初学者'],'我有一点基础').value).toBe('我有一点基础')})
 it('rejects a stale token before opening a question',()=>{expect(()=>prepareProfileInterviewQuestion(start(),{sessionId:'s',callId:'x',questionToken:'stale'})).toThrowError(expect.objectContaining({code:'INTERVIEW_QUESTION_STALE'}))})
})
