import {describe,expect,it} from 'vitest'
import {INTERVIEW_PROBES,activeProject,beginWorkspaceOnboarding,emptyState,normalizeNativeAnswer,prepareProfileInterviewQuestion,probeDefinition,recordProfileInterviewAnswer,workspaceOf} from '../src/index.js'
const start=()=>beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'})
const prepare=(state:ReturnType<typeof start>,callId:string,scaffoldOptions?:any[])=>prepareProfileInterviewQuestion(state,{sessionId:'s',callId,questionToken:activeProject(workspaceOf(state,'ws')).profileInterview.pendingQuestion!.token,scaffoldOptions})
const answer=(state:ReturnType<typeof start>,callId:string,input:{selected?:string[];custom?:string},scaffoldOptions?:any[])=>{const prepared=prepare(state,callId,scaffoldOptions),q=activeProject(workspaceOf(prepared,'ws')).profileInterview.activeQuestion!;return recordProfileInterviewAnswer(prepared,{sessionId:'s',callId,questionId:q.questionId,selected:input.selected??[],custom:input.custom})}
describe('learner-first Profile interview',()=>{
 it('starts with free-text goal.subject and no goal.kind',()=>{const p=activeProject(workspaceOf(start(),'ws'));expect(p.profileInterview.currentProbeId).toBe('goal.subject');expect(INTERVIEW_PROBES.some(x=>String(x.id)==='goal.kind')).toBe(false);expect(probeDefinition('goal.subject').questionMode).toBe('free-text')})
 it('accepts native custom text and advances to scaffolded outcome with a different token',()=>{let s=start(),first=activeProject(workspaceOf(s,'ws')).profileInterview.pendingQuestion!.token;s=prepare(s,'c1');const q=activeProject(workspaceOf(s,'ws')).profileInterview.activeQuestion!;s=recordProfileInterviewAnswer(s,{sessionId:'s',callId:'c1',questionId:q.questionId,selected:[],custom:'简单了解量化交易系统'});const i=activeProject(workspaceOf(s,'ws')).profileInterview;expect(i.probes['goal.subject'].normalizedValue).toBe('简单了解量化交易系统');expect(i.currentProbeId).toBe('goal.outcome');expect(i.pendingQuestion!.token).not.toBe(first)})
 it('does not let ambiguous custom text overwrite a structured field',()=>{const d=probeDefinition('current-foundation.level'),result=normalizeNativeAnswer(d,d.fixedOptions!,['初学者'],'我有一点基础');expect(result).toMatchObject({valid:false,value:null,clarification:true})})
 it.each(['target-outcome.quality-bar','success-criteria.criteria'] as const)('closes free-text uncertainty for %s through an explicit scaffold stage',(probeId)=>{let s=start(),call=0;while(activeProject(workspaceOf(s,'ws')).profileInterview.currentProbeId!==probeId){const current=activeProject(workspaceOf(s,'ws')).profileInterview.currentProbeId!,definition=probeDefinition(current),input=current==='goal.subject'?{custom:'分布式系统'}:current==='goal.outcome'?{selected:['先简单了解它是什么']}:definition.fixedOptions?.length?{selected:[definition.fixedOptions[0]!.label]}:{custom:'有效回答'};s=answer(s,`before-${call++}`,input)}const old=activeProject(workspaceOf(s,'ws')).profileInterview.pendingQuestion!.token;s=answer(s,'uncertain',{custom:'不知道'});let interview=activeProject(workspaceOf(s,'ws')).profileInterview;expect(interview.pendingQuestion).toMatchObject({probeId,stage:'uncertainty-scaffold',mode:'scaffolded-options'});expect(interview.pendingQuestion!.token).not.toBe(old);expect(()=>prepareProfileInterviewQuestion(s,{sessionId:'s',callId:'old',questionToken:old})).toThrowError(expect.objectContaining({code:'INTERVIEW_QUESTION_STALE'}));s=answer(s,'scaffold-choice',{selected:['理解核心概念和完整流程']});interview=activeProject(workspaceOf(s,'ws')).profileInterview;expect(interview.currentProbeId).not.toBe(probeId);expect(interview.probes[probeId].status).toBe('answered')})
 it('persists clarification with a new token and leaves enum value untouched until a canonical choice',()=>{let s=start();s=answer(s,'subject',{custom:'分布式系统'});s=answer(s,'outcome',{selected:['还不确定，请根据入门目标推荐']});s=answer(s,'quality',{custom:'能解释主要概念'});const old=activeProject(workspaceOf(s,'ws')).profileInterview.pendingQuestion!.token;s=answer(s,'ambiguous',{custom:'我有一点基础'});let interview=activeProject(workspaceOf(s,'ws')).profileInterview;expect(interview.pendingQuestion).toMatchObject({stage:'clarification',mode:'fixed-options'});expect(interview.pendingQuestion!.token).not.toBe(old);expect(interview.probes['current-foundation.level'].normalizedValue).toBeNull();expect(structuredClone(s).workspaces.ws!.projects[activeProject(workspaceOf(s,'ws')).id]!.profileInterview.pendingQuestion).toEqual(interview.pendingQuestion);s=answer(s,'clarified',{selected:['有一定基础']});interview=activeProject(workspaceOf(s,'ws')).profileInterview;expect(interview.probes['current-foundation.level'].normalizedValue).toBe('intermediate')})
 it('deterministically normalizes bounded weekly hours but rejects prose',()=>{const d=probeDefinition('time-budget.weekly-hours');expect(normalizeNativeAnswer(d,d.fixedOptions!,[],'每周 7 小时')).toMatchObject({valid:true,value:7});expect(normalizeNativeAnswer(d,d.fixedOptions!,[],'平时有时间就学')).toMatchObject({valid:false,value:null,clarification:true})})
 it('rejects a stale token before opening a question',()=>{expect(()=>prepareProfileInterviewQuestion(start(),{sessionId:'s',callId:'x',questionToken:'stale'})).toThrowError(expect.objectContaining({code:'INTERVIEW_QUESTION_STALE'}))})
})
