import {describe,expect,it} from 'vitest'
import {activeProject,beginWorkspaceOnboarding,createLearnLoopProfileQuestionTool,emptyState,interviewQuestionRequestFingerprint,workspaceOf} from '../src/index.js'
const fixture=()=>{let state=beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'b'});const table={get:()=>state,put:async()=>{},update:async(_id:string,fn:any)=>(state=fn(state))};return{table,state:()=>state}}
describe('tokenized Profile question Tool',()=>{
 it('declares required questionToken and persists custom before returning',async()=>{const f=fixture(),token=activeProject(workspaceOf(f.state(),'ws')).profileInterview.pendingQuestion!.token,tool=createLearnLoopProfileQuestionTool(f.table as any,{ask:async({questions}:any)=>({answers:[{id:questions[0].id,selected:[],custom:'简单了解量化交易系统'}]})},{tailSeq:()=>1} as any) as any;const result=await tool.execute({questionToken:token},{agent:{id:'s'},callId:'c1'} as any);expect(result.status).toBe('next-question-ready');expect(result.nextQuestionToken).not.toBe(token)})
 it('does not call DSH for a stale token',async()=>{const f=fixture(),ask=async()=>{throw Error('opened')},tool=createLearnLoopProfileQuestionTool(f.table as any,{ask},{tailSeq:()=>1} as any) as any;await expect(tool.execute({questionToken:'stale'},{agent:{id:'s'},callId:'c'})).rejects.toMatchObject({code:'INTERVIEW_QUESTION_STALE'})})
 it('replays only an identical request and performs the native side effect once',async()=>{const f=fixture(),token=activeProject(workspaceOf(f.state(),'ws')).profileInterview.pendingQuestion!.token;let asks=0;const tool=createLearnLoopProfileQuestionTool(f.table as any,{ask:async({questions}:any)=>{asks++;return{answers:[{id:questions[0].id,selected:[],custom:'分布式系统'}]} }},{tailSeq:()=>1} as any) as any,first=await tool.execute({questionToken:token},{agent:{id:'s'},callId:'same'} as any),revision=f.state().revision;expect(await tool.execute({questionToken:token},{agent:{id:'s'},callId:'same'} as any)).toEqual(first);expect(asks).toBe(1);expect(f.state().revision).toBe(revision);await expect(tool.execute({questionToken:'different'},{agent:{id:'s'},callId:'same'} as any)).rejects.toMatchObject({code:'IDEMPOTENCY_KEY_REUSED'});await expect(tool.execute({questionToken:token,scaffoldOptions:[{label:'入门了解',level:'overview'},{label:'理解案例',level:'interpret'},{label:'独立应用',level:'independent-use'}]},{agent:{id:'s'},callId:'same'} as any)).rejects.toMatchObject({code:'IDEMPOTENCY_KEY_REUSED'})})
 it('canonicalizes object formatting while preserving option meaning',()=>{const a={questionToken:' token ',scaffoldOptions:[{label:' 入门 ',description:' 简介 ',level:'overview' as const},{label:'应用案例',level:'interpret' as const},{label:'独立实践',level:'independent-use' as const}]},b={scaffoldOptions:[{description:'简介',level:'overview' as const,label:'入门'},{level:'interpret' as const,label:'应用案例'},{level:'independent-use' as const,label:'独立实践'}],questionToken:'token'};expect(interviewQuestionRequestFingerprint(a)).toBe(interviewQuestionRequestFingerprint(b));expect(interviewQuestionRequestFingerprint({...b,scaffoldOptions:b.scaffoldOptions.map((option,index)=>index===1?{...option,label:'不同案例'}:option)})).not.toBe(interviewQuestionRequestFingerprint(b))})
})
