import {describe,expect,it} from 'vitest'
import {activeProject,beginWorkspaceOnboarding,createLearnLoopProfileQuestionTool,emptyState,workspaceOf,type LearnLoopState,type StateTable} from '../src/index.js'

class MemoryTable implements StateTable{constructor(private state:LearnLoopState){}get(){return this.state}async put(_id:string,value:LearnLoopState){this.state=value}async update(_id:string,update:(current:LearnLoopState)=>LearnLoopState){this.state=update(this.state);return this.state}}

describe('LearnLoop-owned native Profile question tool',()=>{
 it('sends Host labels through the real DSH seam and resolves only after persistence and progression',async()=>{const table=new MemoryTable(beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}));let observed:any;const native={ask:async(request:any)=>{observed=request;return{answers:[{id:request.questions[0].id,selected:['掌握一项具体技能']}]}}},sessions={tailSeq:()=>7} as any,tool=createLearnLoopProfileQuestionTool(table,native,sessions) as any;const result=await tool.execute({}, {agent:{id:'s'},callId:'native-1',signal:new AbortController().signal});expect(observed.questions).toEqual([expect.objectContaining({id:'learnloop-profile-goal.kind',options:expect.arrayContaining([expect.objectContaining({label:'掌握一项具体技能'})])})]);expect(result).toEqual({status:'answered',probeId:'goal.kind',nextProbeId:'goal.subject'});const interview=activeProject(workspaceOf(table.get('singleton')!,'ws')).profileInterview;expect(interview.probes['goal.kind'].normalizedValue).toBe('skill');expect(interview.currentProbeId).toBe('goal.subject');expect(interview.activeQuestion).toBeNull()})
 it('uses non-empty custom as the final answer and replays the original receipt',async()=>{const table=new MemoryTable(beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}));let calls=0;const native={ask:async(request:any)=>{calls++;return{answers:[{id:request.questions[0].id,selected:['掌握一项具体技能'],custom:'学习 system prompt 和 tool call 的工程设计'}]}}},tool=createLearnLoopProfileQuestionTool(table,native,{tailSeq:()=>2} as any) as any,exec={agent:{id:'s'},callId:'same',signal:new AbortController().signal};const first=await tool.execute({},exec),revision=table.get('singleton')!.revision;expect(await tool.execute({},exec)).toEqual(first);expect(calls).toBe(1);expect(table.get('singleton')!.revision).toBe(revision);expect(activeProject(workspaceOf(table.get('singleton')!,'ws')).profileInterview.probes['goal.kind'].normalizedValue).toContain('system prompt')})
})
