import {describe,expect,it,vi} from 'vitest';import {readFile} from 'node:fs/promises';import vm from 'node:vm'
async function client(fetch=vi.fn()){let registration:any;const sandbox:any={fetch,crypto:{randomUUID:()=> 'request-id'},window:{__ModuleLoader__:{load(v:any){registration=v}}}};vm.runInNewContext(await readFile('client/bundle.js','utf8'),sandbox);return registration.factory(()=>({createElement(){},useReducer(){return[0,()=>{}]},useEffect(){},useState(){return['',()=>{}]}})).__test}
const task={id:'task',status:'pending'},plan={stages:[{tasks:[task]}]},base:any={workspace:{activeSessionId:'s',revision:4},nextAction:task,activeProject:{id:'project',phase:'active',plans:[plan],execution:null}}
describe('contextual primary action protocol',()=>{
 it('derives every action with one explicit effect',async()=>{const {derivePrimaryLearningAction:derive}=await client(),cases:[any,string,string,boolean][]=[[{activeProject:null},'begin-learning-mode','http-mutation',false],[{...base,activeProject:{...base.activeProject,phase:'interviewing'}},'continue-interview','submit-chat',false],[{...base,activeProject:{...base.activeProject,phase:'profile_review'}},'review-profile','submit-chat',false],[{...base,activeProject:{...base.activeProject,phase:'planning'}},'generate-plan','submit-chat',false],[{...base,activeProject:{...base.activeProject,phase:'plan_review'}},'review-plan','open-view',false],[{...base,workspace:{...base.workspace,activeSessionId:'other'}},'attach-session','http-mutation',false],[base,'start-task','http-mutation',false],[{...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'teaching'}}},'begin-task-check','http-mutation',false],[{...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'awaiting-answer'}}},'awaiting-answer','disabled',true],[{...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'verifying'}}},'verifying','disabled',true],[{...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'needs-revision'}}},'repeat-check','http-mutation',false],[{...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'paused'}}},'resume-task','http-mutation',false],[{...base,nextAction:null,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'passed'}}},'completed','open-view',false],[{...base,activeProject:{...base.activeProject,phase:'completed'}},'completed','open-view',false],[{...base,activeProject:{...base.activeProject,phase:'archived'}},'archived','disabled',true]];for(const [projection,kind,effect,disabled]of cases)expect(derive(projection,'s')).toMatchObject({kind,disabled,effect:{kind:effect}})})
 it('builds action-specific exact request bodies',async()=>{const t=await client(),store={workspaceId:'ws',value:base};expect(t.buildAttachSessionRequest(store,'session-b')).toEqual({action:'attach-session',workspaceId:'ws',sessionId:'session-b',expectedWorkspaceRevision:4,idempotencyKey:'request-id'});expect(t.buildTaskRequest(store,'s','project','task','start-task')).toEqual({action:'start-task',workspaceId:'ws',projectId:'project',sessionId:'s',taskId:'task',expectedWorkspaceRevision:4,idempotencyKey:'request-id'});expect(t.buildBeginLearningModeRequest('s','attempt')).toEqual({action:'begin-learning-mode',sessionId:'s',activationAttemptId:'attempt'})})
 it('opens plan and progress views',async()=>{const t=await client(),store={value:base};await t.executePrimaryAction(store,{}, {effect:{kind:'open-view',view:'plan'}});expect(t.uiState).toMatchObject({dialogOpen:true,selectedView:'plan'});await t.executePrimaryAction(store,{}, {effect:{kind:'open-view',view:'progress'}});expect(t.uiState.selectedView).toBe('progress')})
 it('does not submit checks and preserves a draft created while HTTP is pending',async()=>{let resolve!:Function;const fetch=vi.fn(()=>new Promise(r=>{resolve=r})),t=await client(fetch),store:any={workspaceId:'ws',value:structuredClone(base),listeners:new Set()},input={draft:'',imageIds:[],phase:'plain'},actions={setDraft:vi.fn(),submit:vi.fn()},props={sessionId:'s',inputActions:actions,getCurrentComposerState:()=>input};const pending=t.executePrimaryAction(store,props,{kind:'start-task',taskId:'task',effect:{kind:'http-mutation',command:'start-task',visibleIntent:'start'}});input.draft='new draft';resolve({ok:true,json:async()=>base});await pending;expect(actions.submit).not.toHaveBeenCalled();expect(actions.setDraft).not.toHaveBeenCalled();expect(store.actionError).toContain('操作已完成');const checkStore:any={workspaceId:'ws',value:structuredClone(base),listeners:new Set()};fetch.mockResolvedValueOnce({ok:true,json:async()=>base});await t.executePrimaryAction(checkStore,props,{kind:'begin-task-check',taskId:'task',effect:{kind:'http-mutation',command:'begin-task-check'}});expect(actions.submit).not.toHaveBeenCalled()})
 it('offers pause and skip only while teaching',async()=>{const t=await client(),derive=t.deriveSecondaryLearningActions;expect(derive({...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'teaching'}}}).map((x:any)=>x.kind)).toEqual(['pause-task','skip-task']);expect(derive({...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'awaiting-answer'}}})).toEqual([]);expect(derive({...base,activeProject:{...base.activeProject,execution:{taskId:'task',phase:'verifying'}}})).toEqual([])})
})
