import {describe,expect,it} from 'vitest'
import {activeProject,approveWorkspacePlan,beginWorkspaceOnboarding,commitWorkspaceProfile,confirmWorkspaceProfile,createPlanDraftFromIntent,emptyState,reviseWorkspaceProfilePreferences,workspaceOf} from '../src/index.js'

const profile={goal:'Learn',priorKnowledge:'Some',experienceLevel:'intermediate' as const,knowledgeGaps:[],learningMode:'balanced' as const,practiceCapacity:'light' as const,exampleDensity:'high' as const,weeklyHours:3,constraints:[],successCriteria:['Explain'],unansweredQuestions:[]}
function planning(){let state=beginWorkspaceOnboarding(emptyState(),{workspaceId:'ws',sessionId:'s',expectedRevision:0,idempotencyKey:'begin'}),projectId=workspaceOf(state,'ws').activeProjectId!;state=commitWorkspaceProfile(state,{...profile,workspaceId:'ws',projectId,sessionId:'s',expectedRevision:1,idempotencyKey:'profile'});state=confirmWorkspaceProfile(state,{workspaceId:'ws',projectId,sessionId:'s',expectedRevision:2,profileRevision:1,idempotencyKey:'confirm'});return{state,projectId}}
describe('profile preference recovery and durable receipts',()=>{
 it('reopens explicit preference changes and archives a draft',()=>{let {state,projectId}=planning();state=createPlanDraftFromIntent(state,{sessionId:'s',callId:'draft',plan:{stages:[{title:'One',outcome:'Learn',tasks:[{title:'Example',objective:'See it',activity:'example',acceptanceCriteria:['Explain'],checkPrompt:'Explain',estimateMinutes:10},{title:'Explain',objective:'Explain it',activity:'explain',acceptanceCriteria:['Explain'],checkPrompt:'Explain it',estimateMinutes:10}]}]}});state=reviseWorkspaceProfilePreferences(state,{workspaceId:'ws',projectId,sessionId:'s',expectedRevision:4,idempotencyKey:'preference',changes:{exampleDensity:'standard'},reason:'Learner explicitly requested fewer examples'});const project=activeProject(workspaceOf(state,'ws'));expect(project.phase).toBe('profile_review');expect(project.profileRevision).toBe(2);expect(project.profile?.confirmedAt).toBeNull();expect(project.profile?.learningPreferences.exampleDensity).toBe('standard');expect(project.plans[0]?.status).toBe('archived');expect(reviseWorkspaceProfilePreferences(state,{workspaceId:'ws',projectId,sessionId:'s',expectedRevision:4,idempotencyKey:'preference',changes:{exampleDensity:'standard'},reason:'Learner explicitly requested fewer examples'})).toBe(state)})
 it('replays profile and approval results after phases advance',()=>{let {state,projectId}=planning();const afterConfirm=state;state=commitWorkspaceProfile(state,{...profile,workspaceId:'ws',projectId,sessionId:'s',expectedRevision:1,idempotencyKey:'profile'});expect(state).toBe(afterConfirm);state=createPlanDraftFromIntent(state,{sessionId:'s',callId:'draft',plan:{stages:[{title:'One',outcome:'Learn',tasks:[{title:'Example',objective:'See it',activity:'example',acceptanceCriteria:['Explain'],checkPrompt:'Explain',estimateMinutes:10},{title:'Explain',objective:'Explain it',activity:'explain',acceptanceCriteria:['Explain'],checkPrompt:'Explain it',estimateMinutes:10}]}]}});const plan=activeProject(workspaceOf(state,'ws')).plans[0]!;state=approveWorkspacePlan(state,{workspaceId:'ws',projectId,sessionId:'s',expectedRevision:4,idempotencyKey:'approve',planId:plan.id});const active=state;expect(approveWorkspacePlan(state,{workspaceId:'ws',projectId,sessionId:'s',expectedRevision:4,idempotencyKey:'approve',planId:plan.id})).toBe(active);expect(state.commandReceipts.find(r=>r.idempotencyKey==='approve')?.result).toMatchObject({kind:'plan-approved',planId:plan.id,planVersion:1})})
})
