import {expect,test} from '@playwright/test'
test.describe.configure({mode:'serial'})
async function dismissSetup(page:any){const notice=page.getByRole('dialog').filter({hasText:'Internal Testing Notice'});if(await notice.isVisible().catch(()=>false)){const proceed=notice.getByRole('button',{name:'Continue'});if(await proceed.isVisible().catch(()=>false))await proceed.click()}const configure=page.getByText('Configure later',{exact:true});if(await configure.isVisible().catch(()=>false))await configure.click()}
test('LearnLoop loads and sidebar opens its root dialog from a blank Session',async({page})=>{const errors:string[]=[];page.on('console',message=>{if(message.type()==='error'&&/LearnLoop/i.test(message.text()))errors.push(message.text())});await page.goto('/');await dismissSetup(page);await expect(page.getByRole('button',{name:'学习计划'})).toBeVisible();await page.getByRole('button',{name:'学习计划'}).click();const dialog=page.getByRole('dialog',{name:'LearnLoop'});await expect(dialog).toBeVisible();const tab=dialog.getByRole('tab',{name:/学习计划.*Learning Plan/});await expect(tab).toHaveAttribute('aria-selected','true');await expect(page.getByText('正在同步 LearnLoop… / Syncing LearnLoop…')).not.toBeVisible({timeout:10_000});await expect(page.getByText(/还没有学习项目|学习计划 \/ Learning Plan|未找到 Workspace/).first()).toBeVisible();expect(errors).toEqual([])})
test('LearnLoop settings contains its persisted fields rather than a version placeholder',async({page})=>{await page.goto('/');await dismissSetup(page);await page.getByRole('button',{name:/Settings|设置/}).click();await page.getByText('LearnLoop',{exact:true}).click();await expect(page.getByText('LearnLoop 设置 / Settings')).toBeVisible();await expect(page.getByRole('combobox',{name:'language'})).toBeVisible();await expect(page.getByRole('spinbutton',{name:'weeklyHours'})).toBeVisible();await expect(page.getByRole('combobox',{name:'strictness'})).toBeVisible();for(const field of ['autoMinorAdjustments','showModeExplanation','antiDependency'])await expect(page.getByRole('checkbox',{name:field})).toBeVisible();await expect(page.getByText(/已保存的学习计划 \/ Saved learning plans/)).toBeVisible()})

test.describe('provisioned learner-first Profile interview',()=>{
 test('custom learning subject receives scaffolded outcome options',async({page})=>{const consoleErrors:string[]=[],pageErrors:string[]=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>pageErrors.push(e.message));await page.goto('/');await dismissSetup(page);const launcher=page.getByRole('button',{name:/开启学习模式 \/ Start learning mode/});await expect(launcher).toBeVisible();await launcher.click();await expect(page.getByText(/你现在想学什么/)).toBeVisible({timeout:30_000});const custom=page.locator('textarea').filter({visible:true}).last();await custom.fill('简单了解量化交易系统');await page.getByRole('button',{name:/Submit|提交|Send/}).last().click();await expect(page.getByText('了解量化交易的基本概念和完整流程',{exact:true})).toBeVisible({timeout:30_000});const uncertain=page.getByText('还不确定，请根据入门目标推荐',{exact:true});await expect(uncertain).toBeVisible();await uncertain.click();await expect(page.getByText(/哪一种可理解的结果/)).toBeVisible({timeout:30_000});await expect(page.getByText(/INTERVIEW_QUESTION_CONTRACT_INVALID|普通聊天|fallback/i)).toHaveCount(0);await page.reload();await dismissSetup(page);await expect(page.getByText(/哪一种可理解的结果/)).toBeVisible({timeout:30_000});expect(consoleErrors).toEqual([]);expect(pageErrors).toEqual([])})
})
