import { randomUUID } from 'node:crypto'
import { z } from 'zod'
import type { DomainSpec } from '@deepseek-ai/dsh-storage-domain'
import type { AdjustmentProposal, Evidence, GeneratedPlanInput, LearnLoopState, LearningPreferences, MasteryLevel, PlanOperation, PlanVersion, StateTable, TaskState } from './types.js'
const now=()=>new Date().toISOString(), id=(p:string)=>`${p}_${randomUUID()}`
export const DEFAULT_PREFERENCES: LearningPreferences={mode:'balanced',practiceCapacity:'light',explanationDepth:'standard',exampleDensity:'standard',additionalNotes:''}
const preferenceSchema=z.object({mode:z.enum(['knowledge-first','balanced','practice-first']),practiceCapacity:z.enum(['none','light','full']),explanationDepth:z.enum(['standard','deep']),exampleDensity:z.enum(['standard','high']),additionalNotes:z.string().max(2000)}).strict()
const taskState=z.enum(['pending','active','blocked','completed','skipped']), kind=z.enum(['lesson','worked-example','discussion','exercise','implementation']), completion=z.object({kind:z.enum(['short-answer','reflection','artifact']),prompt:z.string()})
const taskSchema=z.object({id:z.string(),title:z.string(),objective:z.string(),acceptanceCriteria:z.array(z.string()),estimateMinutes:z.number().int().positive(),status:taskState,conceptIds:z.array(z.string()),dependsOn:z.array(z.string()),kind,completion})
const operationSchema=z.discriminatedUnion('type',[z.object({type:z.literal('update-task'),taskId:z.string(),patch:z.object({title:z.string().optional(),objective:z.string().optional(),acceptanceCriteria:z.array(z.string()).optional(),estimateMinutes:z.number().int().positive().optional(),status:taskState.optional()}).strict()}),z.object({type:z.literal('move-task'),taskId:z.string(),toStageId:z.string(),beforeTaskId:z.string().optional()})])
const stateV2Schema:z.ZodType<LearnLoopState>=z.object({schemaVersion:z.literal(2),revision:z.number().int().nonnegative(),project:z.object({id:z.string(),title:z.string(),goal:z.string(),experience:z.string(),weeklyHours:z.number().int().min(1).max(80),status:z.enum(['active','archived']),createdAt:z.string(),sessionId:z.string().nullable(),learningPreferences:preferenceSchema}).nullable(),plans:z.array(z.object({id:z.string(),version:z.number().int().positive(),status:z.enum(['draft','active','superseded','archived']),createdAt:z.string(),stages:z.array(z.object({id:z.string(),title:z.string(),tasks:z.array(taskSchema)}))})),evidence:z.array(z.object({id:z.string(),idempotencyKey:z.string(),conceptId:z.string(),kind:z.enum(['explanation','pseudocode','implementation','hypothesis','assessment','reflection']),summary:z.string(),source:z.object({sessionId:z.string(),messageRange:z.string()}),confidence:z.number().min(0).max(1),createdAt:z.string()})),mastery:z.array(z.object({conceptId:z.string(),title:z.string(),level:z.enum(['unassessed','introduced','practicing','demonstrated','mastered']),evidenceIds:z.array(z.string()),rationale:z.string(),updatedAt:z.string()})),assessments:z.array(z.object({id:z.string(),conceptId:z.string(),result:z.enum(['needs-work','passed','excellent']),explanation:z.string(),evidenceId:z.string(),createdAt:z.string()})),adjustments:z.array(z.object({id:z.string(),idempotencyKey:z.string(),impact:z.enum(['minor','major']),state:z.enum(['proposed','applied','rejected','reverted']),reason:z.string(),diff:z.array(z.string()),operations:z.array(operationSchema),inverseOperations:z.array(operationSchema).optional(),createdAt:z.string(),appliedPlanVersion:z.number().optional(),revertedPlanVersion:z.number().optional()})),events:z.array(z.object({id:z.string(),stableId:z.string(),type:z.string(),summary:z.string(),createdAt:z.string()})),settings:z.object({language:z.enum(['zh-CN','en']),weeklyHours:z.number().int().min(1).max(80),strictness:z.enum(['supportive','balanced','strict']),autoMinorAdjustments:z.boolean(),showModeExplanation:z.boolean(),antiDependency:z.boolean()}),misconceptions:z.array(z.string()),reviewQueue:z.array(z.string())}).strict()
type LegacyState=Omit<LearnLoopState,'schemaVersion'|'project'|'plans'>&{schemaVersion:1;project:(Omit<NonNullable<LearnLoopState['project']>,'sessionId'|'learningPreferences'>)|null;plans:Array<Omit<PlanVersion,'stages'>&{stages:Array<{id:string;title:string;tasks:Array<Omit<PlanVersion['stages'][number]['tasks'][number],'kind'|'completion'>>}>}>}
export function migrateStateV1ToV2(value: LegacyState): LearnLoopState {
  return {
    ...value,
    schemaVersion: 2,
    project: value.project ? { ...value.project, sessionId: null, learningPreferences: { ...DEFAULT_PREFERENCES } } : null,
    plans: value.plans.map(plan => ({
      ...plan,
      stages: plan.stages.map(stage => ({
        ...stage,
        tasks: stage.tasks.map(task => ({
          ...task,
          kind: 'lesson' as const,
          completion: { kind: 'short-answer' as const, prompt: `请简要说明：${task.acceptanceCriteria.join('；')}` },
        })),
      })),
    })),
  }
}
const persistedSchema=z.preprocess(value=>{if(value&&typeof value==='object'&&'schemaVersion'in value&&(value as {schemaVersion:unknown}).schemaVersion===1)return migrateStateV1ToV2(value as LegacyState);return value},stateV2Schema)
// The storage unit version describes the backend's physical format, not the
// schemaVersion stored inside each LearnLoop value. Keep it at 1 so existing
// installations can open their unit and let persistedSchema migrate v1 data.
export const learnLoopDomainSpec={name:'learnloop',version:1,tables:{state:{valueSchema:persistedSchema}}} as const satisfies DomainSpec
export function emptyState(revision=0):LearnLoopState{return {schemaVersion:2,revision,project:null,plans:[],evidence:[],mastery:[],assessments:[],adjustments:[],events:[],misconceptions:[],reviewQueue:[],settings:{language:'zh-CN',weeklyHours:10,strictness:'balanced',autoMinorAdjustments:true,showModeExplanation:false,antiDependency:true}}}
function event(type:string,summary:string,stableId=id('evt')){return{id:id('event'),stableId,type,summary,createdAt:now()}}
function activePlan(s:LearnLoopState){const p=s.plans.filter(x=>x.status==='active');if(p.length!==1)throw Error('project must have exactly one active plan');return p[0]!}
const bump=(s:LearnLoopState):LearnLoopState=>({...s,revision:s.revision+1})
export function initializeProject(s:LearnLoopState,input:{goal:string;experience:string;weeklyHours:number;sessionId:string;learningPreferences:LearningPreferences;idempotencyKey:string}){if(s.events.some(x=>x.stableId===input.idempotencyKey))return s;if(s.project)throw Error('project already exists');const createdAt=now(),goal=input.goal.trim(),sessionId=input.sessionId.trim();if(!goal||!sessionId)throw Error('project goal and sessionId are required');const plan:PlanVersion={id:id('plan'),version:1,status:'active',createdAt,stages:[]};return bump({...s,project:{id:id('project'),title:goal.slice(0,40),goal,experience:input.experience.trim(),weeklyHours:input.weeklyHours,status:'active',createdAt,sessionId,learningPreferences:preferenceSchema.parse(input.learningPreferences)},plans:[plan],events:[...s.events,event('learnloop/project-created','Learning project created',input.idempotencyKey),event('learnloop/plan-generation-requested','Plan generation requested')]})}
export function bindProjectSession(s:LearnLoopState,input:{sessionId:string;idempotencyKey:string}){if(s.events.some(x=>x.stableId===input.idempotencyKey))return s;if(!s.project)throw Error('project does not exist');if(s.project.sessionId!==null)throw Error('project is already bound');const sessionId=input.sessionId.trim();if(!sessionId)throw Error('project sessionId is required');return bump({...s,project:{...s.project,sessionId},events:[...s.events,event('learnloop/session-bound','Project bound to DSH session',input.idempotencyKey)]})}
const clean=(v:string,l:string,max:number)=>{const x=v.trim();if(!x||x.length>max)throw Error(`${l} must be non-empty and at most ${max} characters`);return x}, keyPattern=/^[a-z0-9][a-z0-9-]{0,63}$/
export function publishGeneratedPlan(s:LearnLoopState,input:GeneratedPlanInput&{idempotencyKey:string}){if(s.events.some(x=>x.stableId===input.idempotencyKey))return s;if(!s.project)throw Error('project does not exist');const plan=activePlan(s);if(plan.stages.length)throw Error('project plan is already published');if(input.stages.length<1||input.stages.length>8)throw Error('project plan must contain 1 to 8 stages');const sk=new Set<string>(),tk=new Set<string>(),ck=new Set<string>();const normalized=input.stages.map(stage=>{const stageKey=clean(stage.key,'stage key',64);if(!keyPattern.test(stageKey)||sk.has(stageKey))throw Error('stage key is invalid or duplicate');sk.add(stageKey);if(!stage.tasks.length)throw Error('project plan stage must contain a task');return{key:stageKey,title:clean(stage.title,'stage title',200),tasks:stage.tasks.map(task=>{const taskKey=clean(task.key,'task key',64),conceptKey=clean(task.conceptKey,'concept key',64);if(!keyPattern.test(taskKey)||tk.has(taskKey))throw Error('duplicate task key');if(!keyPattern.test(conceptKey)||ck.has(conceptKey))throw Error('duplicate concept key');tk.add(taskKey);ck.add(conceptKey);if(task.acceptanceCriteria.length<1||task.acceptanceCriteria.length>8)throw Error('task must contain 1 to 8 acceptance criteria');if(!Number.isInteger(task.estimateMinutes)||task.estimateMinutes<10||task.estimateMinutes>480)throw Error('task estimateMinutes must be between 10 and 480');return{...task,key:taskKey,conceptKey,title:clean(task.title,'task title',300),objective:clean(task.objective,'task objective',2000),conceptTitle:clean(task.conceptTitle,'concept title',300),acceptanceCriteria:task.acceptanceCriteria.map(x=>clean(x,'acceptance criterion',500)),completion:{...task.completion,prompt:clean(task.completion.prompt,'completion prompt',1000)}}})}});const tasks=normalized.flatMap(x=>x.tasks);if(tasks.length<2||tasks.length>20)throw Error('project plan must contain 2 to 20 tasks');for(const t of tasks){if(new Set(t.dependsOn).size!==t.dependsOn.length||t.dependsOn.includes(t.key))throw Error('task cannot depend on itself or duplicate dependency');if(t.dependsOn.some(d=>!tk.has(d)))throw Error('task dependency does not exist')}
const pref=s.project.learningPreferences;if(pref.practiceCapacity==='none'&&tasks.some(t=>t.kind==='implementation'))throw Error('practiceCapacity none forbids implementation tasks');if(pref.practiceCapacity!=='full'&&tasks.some(t=>t.completion.kind==='artifact'))throw Error('practiceCapacity forbids artifact completion');if(pref.mode==='knowledge-first'){if(tasks.filter(t=>t.kind==='lesson'||t.kind==='worked-example').length<Math.ceil(tasks.length/2))throw Error('knowledge-first requires at least half lesson or worked-example tasks');if(normalized.some(st=>!st.tasks.some(t=>t.kind==='lesson'||t.kind==='worked-example')))throw Error('knowledge-first requires a lesson or worked-example in every stage')}
const visiting=new Set<string>(),visited=new Set<string>(),byKey=new Map(tasks.map(t=>[t.key,t]));const visit=(k:string)=>{if(visiting.has(k))throw Error('task dependency graph contains a cycle');if(visited.has(k))return;visiting.add(k);for(const d of byKey.get(k)!.dependsOn)visit(d);visiting.delete(k);visited.add(k)};tasks.forEach(t=>visit(t.key));const first=tasks.find(t=>!t.dependsOn.length);if(!first)throw Error('project plan has no executable task');const createdAt=now(),stages=normalized.map(st=>({id:`stage-${st.key}`,title:st.title,tasks:st.tasks.map(t=>({id:`task-${t.key}`,title:t.title,objective:t.objective,acceptanceCriteria:t.acceptanceCriteria,estimateMinutes:t.estimateMinutes,status:t.key===first.key?'active' as const:'pending' as const,conceptIds:[`concept-${t.conceptKey}`],dependsOn:t.dependsOn.map(d=>`concept-${byKey.get(d)!.conceptKey}`),kind:t.kind,completion:t.completion}))}));return bump({...s,plans:s.plans.map(p=>p.id===plan.id?{...p,stages}:p),mastery:tasks.map(t=>({conceptId:`concept-${t.conceptKey}`,title:t.conceptTitle,level:'introduced' as const,evidenceIds:[],rationale:'Introduced by generated plan; no evidence yet.',updatedAt:createdAt})),events:[...s.events,event('learnloop/plan-generated','Generated plan published',input.idempotencyKey),event('learnloop/task-activated',`First task activated: ${first.title}`)]})}
export function nextAction(s:LearnLoopState){if(!s.project)return null;const tasks=activePlan(s).stages.flatMap(x=>x.tasks);return tasks.find(t=>t.status==='active')??tasks.find(t=>t.status==='pending'&&t.dependsOn.every(d=>tasks.some(x=>x.conceptIds.includes(d)&&x.status==='completed')))??null}
export function startTask(s:LearnLoopState,input:{taskId:string;idempotencyKey:string}){if(s.events.some(x=>x.stableId===input.idempotencyKey))return s;if(!s.project)throw Error('project does not exist');const plan=activePlan(s),tasks=plan.stages.flatMap(x=>x.tasks),task=tasks.find(x=>x.id===input.taskId);if(!task)throw Error('task not found');if(task.status==='active')return s;if(task.status!=='pending'||nextAction(s)?.id!==task.id||tasks.some(x=>x.status==='active')||!task.dependsOn.every(d=>tasks.some(x=>x.conceptIds.includes(d)&&x.status==='completed')))throw Error('task is locked');const changed={...plan,stages:plan.stages.map(st=>({...st,tasks:st.tasks.map(x=>x.id===task.id?{...x,status:'active' as const}:x)}))};return bump({...s,plans:s.plans.map(x=>x.id===plan.id?changed:x),events:[...s.events,event('learnloop/task-started',`Task started: ${task.title}`,input.idempotencyKey)]})}
export function setTaskState(s:LearnLoopState,input:{taskId:string;status:TaskState;idempotencyKey:string}){if(s.events.some(x=>x.stableId===input.idempotencyKey))return s;if(input.status==='active'||input.status==='completed'||input.status==='pending')throw Error(`task status ${input.status} requires a domain command`);const plan=activePlan(s),task=plan.stages.flatMap(x=>x.tasks).find(x=>x.id===input.taskId);if(!task)throw Error('task not found');if(!['pending','active','blocked'].includes(task.status)||task.status===input.status)throw Error('task transition is invalid');const changed={...plan,stages:plan.stages.map(st=>({...st,tasks:st.tasks.map(x=>x.id===task.id?{...x,status:input.status}:x)}))};return bump({...s,plans:s.plans.map(x=>x.id===plan.id?changed:x),events:[...s.events,event('learnloop/task-changed',`Task status changed to ${input.status}`,input.idempotencyKey)]})}
function masteryFor(e:Evidence[]):{level:MasteryLevel;rationale:string}{const high=e.filter(x=>x.confidence>=.75),k=new Set(high.map(x=>x.kind));if(high.length>=3&&(k.has('assessment')||k.has('implementation')))return{level:'mastered',rationale:'Multiple strong evidence items.'};if(high.length>=2)return{level:'demonstrated',rationale:'Two strong evidence items.'};if(e.length)return{level:'practicing',rationale:`${e.length} evidence item(s).`};return{level:'introduced',rationale:'No evidence yet.'}}
export function recordEvidence(s:LearnLoopState,input:Omit<Evidence,'id'|'createdAt'>){if(s.evidence.some(x=>x.idempotencyKey===input.idempotencyKey))return s;if(!s.mastery.some(x=>x.conceptId===input.conceptId))throw Error('concept not found');const saved={...input,id:id('evidence'),createdAt:now()},evidence=[...s.evidence,saved],mastery=s.mastery.map(m=>m.conceptId===saved.conceptId?{...m,...masteryFor(evidence.filter(x=>x.conceptId===m.conceptId)),evidenceIds:evidence.filter(x=>x.conceptId===m.conceptId).map(x=>x.id),updatedAt:now()}:m);return bump({...s,evidence,mastery,events:[...s.events,event('learnloop/evidence-recorded','Evidence recorded',input.idempotencyKey)]})}
export function completeTaskWithEvidence(s:LearnLoopState,input:{idempotencyKey:string;taskId:string;conceptId:string;kind:Evidence['kind'];summary:string;source:Evidence['source'];confidence:number}){if(s.events.some(x=>x.stableId===input.idempotencyKey))return s;const plan=activePlan(s),task=plan.stages.flatMap(x=>x.tasks).find(x=>x.id===input.taskId);if(!task)throw Error('task not found');if(task.status==='completed')throw Error('task is already completed');if(task.status!=='active'||nextAction(s)?.id!==task.id)throw Error('task must be the current active task');if(!task.conceptIds.includes(input.conceptId))throw Error(s.mastery.some(x=>x.conceptId===input.conceptId)?'concept does not belong to task':'concept not found');const expected={ 'short-answer':'explanation',reflection:'reflection',artifact:'implementation'} as const;if(input.kind!==expected[task.completion.kind])throw Error('task completion evidence kind does not match requirement');const withEvidence=recordEvidence(s,input),p=activePlan(withEvidence),changed={...p,stages:p.stages.map(st=>({...st,tasks:st.tasks.map(x=>x.id===task.id?{...x,status:'completed' as const}:x)}))};return {...withEvidence,plans:withEvidence.plans.map(x=>x.id===p.id?changed:x),events:withEvidence.events.map(x=>x.stableId===input.idempotencyKey?{...x,type:'learnloop/task-completed-with-evidence'}:x)} }
export function discardCurrentProject(s:LearnLoopState,key:string){if(s.events.some(x=>x.stableId===key))return s;if(!s.project)throw Error('project does not exist');return bump({...s,project:null,plans:[],evidence:[],mastery:[],assessments:[],adjustments:[],misconceptions:[],reviewQueue:[],events:[event('learnloop/project-discarded','Project discarded',key)]})}
// Plan adjustments remain versioned and never activate/complete tasks through this generic path.
function applyOperations(plan:PlanVersion,ops:PlanOperation[]){const stages=structuredClone(plan.stages),inverse:PlanOperation[]=[];for(const op of ops){const ss=stages.find(s=>s.tasks.some(t=>t.id===op.taskId)),task=ss?.tasks.find(t=>t.id===op.taskId);if(!ss||!task)throw Error('adjustment task not found');if(op.type==='update-task'){if(op.patch.status==='active'||op.patch.status==='completed')throw Error('adjustment cannot bypass task gate');const old=Object.fromEntries(Object.keys(op.patch).map(k=>[k,structuredClone(task[k as keyof typeof task])])) as Extract<PlanOperation,{type:'update-task'}>['patch'];inverse.unshift({type:'update-task',taskId:task.id,patch:old});Object.assign(task,structuredClone(op.patch))}else{const target=stages.find(s=>s.id===op.toStageId);if(!target)throw Error('adjustment target stage not found');const ix=ss.tasks.indexOf(task),before=ss.tasks[ix+1]?.id;ss.tasks.splice(ix,1);target.tasks.splice(op.beforeTaskId?target.tasks.findIndex(t=>t.id===op.beforeTaskId):target.tasks.length,0,task);inverse.unshift({type:'move-task',taskId:task.id,toStageId:ss.id,...(before?{beforeTaskId:before}:{})})}}return{stages,inverse}}
function versionPlan(s:LearnLoopState,ops:PlanOperation[]){const current=activePlan(s),a=applyOperations(current,ops),version=Math.max(...s.plans.map(p=>p.version))+1,replacement={...structuredClone(current),id:id('plan'),version,createdAt:now(),status:'active' as const,stages:a.stages};return{state:{...s,plans:[...s.plans.map(p=>p.id===current.id?{...p,status:'superseded' as const}:p),replacement]},version,inverse:a.inverse}}
export function proposeAdjustment(s:LearnLoopState,input:{impact:'minor'|'major';reason:string;diff:string[];operations:PlanOperation[];idempotencyKey:string}){if(s.adjustments.some(x=>x.idempotencyKey===input.idempotencyKey))return s;if(!input.operations.length)throw Error('adjustment requires at least one operation');const auto=input.impact==='minor'&&s.settings.autoMinorAdjustments;let proposal:AdjustmentProposal={id:id('adjustment'),...input,state:auto?'applied':'proposed',createdAt:now()},result={...s,adjustments:[...s.adjustments,proposal]};if(auto){const a=versionPlan(result,input.operations);proposal={...proposal,appliedPlanVersion:a.version,inverseOperations:a.inverse};result={...a.state,adjustments:a.state.adjustments.map(x=>x.id===proposal.id?proposal:x)}}return bump({...result,events:[...result.events,event(auto?'learnloop/adjustment-applied':'learnloop/adjustment-proposed',input.reason,input.idempotencyKey)]})}
export function decideAdjustment(s:LearnLoopState,aid:string,decision:'apply'|'reject'|'revert',key:string){if(s.events.some(x=>x.stableId===key))return s;const target=s.adjustments.find(x=>x.id===aid);if(!target)throw Error('adjustment not found');let result=s,patch:Partial<AdjustmentProposal>;if(decision==='apply'){if(target.state!=='proposed')throw Error('adjustment decision invalid');const a=versionPlan(s,target.operations);result=a.state;patch={state:'applied',appliedPlanVersion:a.version,inverseOperations:a.inverse}}else if(decision==='revert'){if(target.state!=='applied')throw Error('adjustment decision invalid');const a=versionPlan(s,target.inverseOperations??[]);result=a.state;patch={state:'reverted',revertedPlanVersion:a.version}}else{if(target.state!=='proposed')throw Error('adjustment decision invalid');patch={state:'rejected'}}return bump({...result,adjustments:result.adjustments.map(x=>x.id===aid?{...x,...patch}:x),events:[...result.events,event(`learnloop/adjustment-${decision}`,'Adjustment decision',key)]})}
export function updateSettings(s:LearnLoopState,settings:LearnLoopState['settings'],key:string){if(s.events.some(x=>x.stableId===key))return s;return bump({...s,settings,events:[...s.events,event('learnloop/settings-changed','Settings updated',key)]})}
export function resetState(s:LearnLoopState,key:string){const x=emptyState(s.revision+1);x.events=[event('learnloop/reset','State reset',key)];return x}
export async function ensureState(table:StateTable){const current=table.get('singleton');if(current)return current;const fresh=emptyState();await table.put('singleton',fresh);return fresh}
