import { createHash } from 'node:crypto'
import { canonicalJson, createEvidenceCandidate, LearnLoopDomainError } from './domain.js'
import type { StateTable } from './types.js'
export interface DirectMessage{id:string;source:{kind:string};content:Array<{type:string;text?:string}>}
export interface PreStepEnter{kind:'enter';messages:DirectMessage[]}
export type PreStepDecision=PreStepEnter|{kind:string}
export function hashDirectMessages(messages:DirectMessage[]){return createHash('sha256').update(canonicalJson(messages.map(m=>({id:m.id,source:m.source,content:m.content})))).digest('hex')}
export function extractTextAnswer(messages:DirectMessage[]){const direct=messages.filter(m=>m.source.kind==='user');if(!direct.length)return null;const texts=direct.map(m=>{if(m.content.some(b=>b.type!=='text')||m.content.some(b=>b.type==='text'&&typeof b.text!=='string'))throw new LearnLoopDomainError('ANSWER_UNSUPPORTED','This check currently supports text answers only.');return m.content.map(b=>b.text?.trim()??'').filter(Boolean).join('\n')});const answerText=texts.filter(Boolean).join('\n\n---\n\n');if(!answerText||answerText.length>20000)throw new LearnLoopDomainError('ANSWER_UNSUPPORTED','Answer must contain 1 to 20,000 text characters.');return{messages:direct,answerText,contentHash:hashDirectMessages(direct)}}
export async function capturePreStepAnswer(table:StateTable,agentId:string,signal:AbortSignal,next:()=>Promise<PreStepDecision>){const decision=await next();if(decision.kind!=='enter'||signal.aborted||!('messages' in decision))return decision;const state=table.get('singleton');if(state?.project?.sessionId!==agentId||state.execution?.phase!=='awaiting-answer')return decision;const answer=extractTextAnswer(decision.messages);if(!answer)return decision;await table.update('singleton',current=>createEvidenceCandidate(current,{sessionId:agentId,messageIds:answer.messages.map(m=>m.id),answerText:answer.answerText,contentHash:answer.contentHash,eventSeqs:[]}));return decision}
export function createSessionQueue(){const tails=new Map<string,Promise<void>>();return function enqueue(sessionId:string,work:()=>Promise<void>){const previous=tails.get(sessionId)??Promise.resolve();const next=previous.then(work,work).finally(()=>{if(tails.get(sessionId)===next)tails.delete(sessionId)});tails.set(sessionId,next);return next}}
export function enrichCandidateEvent(state:ReturnType<StateTable['get']> extends infer T?Exclude<T,undefined>:never,sessionId:string,message:DirectMessage,seq:number){if(state.project?.sessionId!==sessionId||message.source.kind!=='user')return state;const candidate=state.evidenceCandidates.find(c=>c.status==='pending-verification'&&c.source.messageIds.includes(message.id));if(!candidate)return state;if(candidate.source.eventSeqs.includes(seq))return state;if(hashDirectMessages([message])!==candidate.source.contentHash&&candidate.source.messageIds.length===1)throw new LearnLoopDomainError('EVIDENCE_MISMATCH','Candidate source hash mismatch.');return{...state,revision:state.revision+1,evidenceCandidates:state.evidenceCandidates.map(c=>c.id===candidate.id?{...c,source:{...c.source,eventSeqs:[...c.source.eventSeqs,seq]}}:c)}}
