import {createHash} from 'node:crypto'
import {createUserMessage, type UserMessage} from '@deepseek-ai/dsh-llm'
import type {PreStepDecision} from '@deepseek-ai/dsh-agent'
import {canonicalJson, LearnLoopDomainError} from './domain.js'
import {activeProject, createEvidenceCandidate, workspaceForSession} from './workspace.js'
import {learnLoopStateSchema, type StateTable} from './types.js'
export type DirectMessage=Pick<UserMessage,'id'|'source'|'content'>
export const hashDirectMessages=(messages:DirectMessage[])=>createHash('sha256').update(canonicalJson(messages.map(m=>({id:m.id,source:m.source,content:m.content})))).digest('hex')
export function extractTextAnswer(messages:DirectMessage[]){const direct=messages.filter(m=>m.source.kind==='user');if(!direct.length)return null;const answerText=direct.map(m=>{if(m.content.some(b=>b.type!=='text'))throw new LearnLoopDomainError('ANSWER_UNSUPPORTED','Only text answers are supported.');return m.content.map(b=>b.type==='text'?b.text.trim():'').filter(Boolean).join('\n')}).filter(Boolean).join('\n\n---\n\n');if(!answerText||answerText.length>20_000)throw new LearnLoopDomainError('ANSWER_UNSUPPORTED','Answer length is invalid.');return{messages:direct,answerText,contentHash:hashDirectMessages(direct)}}
export async function capturePreStepAnswer(table:StateTable,agentId:string,signal:AbortSignal,next:()=>Promise<PreStepDecision>){const decision=await next();if(decision.kind!=='enter'||signal.aborted)return decision;const state=table.get('singleton');if(!state)return decision;let project;try{project=activeProject(workspaceForSession(state,agentId))}catch{return decision}if(project.execution?.phase!=='awaiting-answer')return decision;const answer=extractTextAnswer(decision.messages);if(!answer)return decision;const updated=await table.update('singleton',s=>createEvidenceCandidate(s,{sessionId:agentId,messageIds:answer.messages.map(m=>m.id),answerText:answer.answerText,contentHash:answer.contentHash,eventSeqs:[]}));const workspace=workspaceForSession(updated,agentId),changed=activeProject(workspace),candidate=changed.evidenceCandidates.find(c=>c.id===changed.execution?.candidateId),plan=changed.plans.find(p=>p.id===changed.activePlanId),task=plan?.stages.flatMap(s=>s.tasks).find(t=>t.id===candidate?.taskId);if(!candidate||!task)throw new LearnLoopDomainError('CANDIDATE_NOT_READY','Verifier context could not be assembled.');const context=createUserMessage({source:{kind:'plugin',plugin:'learnloop',form:'instructions'},content:[{type:'text',text:`LEARNLOOP_VERIFIER_CONTEXT_V1\nHost-selected candidate answer: ${candidate.answerText}\nAcceptance criteria: ${JSON.stringify(task.acceptanceCriteria)}\nCurrent session=${agentId}; project=${changed.id}; task=${task.id}; candidate=${candidate.id}.\nVerifier policy: call learnloop_assess_answer exactly once, cover every criterion index exactly once, and do not teach or advance tasks while verification is pending. Host owns and validates every identity.`}]});return{kind:'enter' as const,messages:[...decision.messages,context]}}
export function enrichCandidateEvent(state:ReturnType<StateTable['get']> extends infer T?Exclude<T,undefined>:never,sessionId:string,message:DirectMessage,seq:number){if(message.source.kind!=='user')return state;let workspace;try{workspace=workspaceForSession(state,sessionId)}catch{return state}const project=activeProject(workspace),candidate=project.evidenceCandidates.find(c=>c.status==='pending-verification'&&c.source.messageIds.includes(message.id));if(!candidate||candidate.source.eventSeqs.includes(seq))return state;const changed={...project,evidenceCandidates:project.evidenceCandidates.map(c=>c.id===candidate.id?{...c,source:{...c.source,eventSeqs:[...c.source.eventSeqs,seq]}}:c)};return learnLoopStateSchema.parse({...state,revision:state.revision+1,workspaces:{...state.workspaces,[workspace.workspaceId]:{...workspace,revision:workspace.revision+1,projects:{...workspace.projects,[project.id]:changed}}}})}
