import type {IncomingMessage,ServerResponse} from 'node:http'
import {z} from 'zod'
import {emptyState,LearnLoopDomainError} from './domain.js'
import {activeProject,attachWorkspaceSession,beginTaskCheck,beginWorkspaceOnboarding,cancelTaskCheck,clearProject,nextAction,pauseTask,restoreSkippedTask,requestWorkspaceProfileRevision,requestWorkspacePlanRevision,confirmWorkspaceProfile,approveWorkspacePlan,resumeTask,skipTask,startTask,workspaceOf} from './workspace.js'
import {settingsSchema, type LearnLoopState, type StateTable} from './types.js'
import type {CanonicalWorkspaceContext} from './workspace-identity.js'
export const API_PATH='/learnloop/api/v3/state';export const EXPORT_PATH='/learnloop/api/v3/export';export const MANAGE_PATH='/learnloop/api/v3/manage'
const domainStatus=(code:LearnLoopDomainError['code'])=>{if(['WORKSPACE_MISMATCH','SESSION_MISMATCH','EXPORT_FORBIDDEN'].includes(code))return 403;if(['PROJECT_NOT_FOUND','TASK_NOT_FOUND','CANDIDATE_NOT_FOUND','ADJUSTMENT_NOT_FOUND','WORKSPACE_NOT_FOUND'].includes(code))return 404;if(['INVALID_PLAN','INVALID_ADJUSTMENT','ASSESSMENT_INVALID','ANSWER_UNSUPPORTED'].includes(code))return 422;if(code==='SESSION_NOT_LIVE')return 503;return 409}
const json=(res:ServerResponse,status:number,value:unknown,headers:Record<string,string>={})=>{const body=JSON.stringify(value);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(body)}
export function projectState(state:LearnLoopState,workspaceId:string){const workspace=workspaceOf(state,workspaceId),project=workspace.activeProjectId?workspace.projects[workspace.activeProjectId]??null:null,execution=project?.execution;return{schemaVersion:state.schemaVersion,rootRevision:state.revision,settings:state.settings,workspace,activeProject:project,nextAction:project?nextAction(project):null,availableActions:{canPauseCurrentTask:execution?.phase==='teaching',canSkipCurrentTask:execution?.phase==='teaching',recoverableSkippedTaskId:null}}}
const common={workspaceId:z.string().trim().min(1),projectId:z.string().trim().min(1),sessionId:z.string().trim().min(1),expectedWorkspaceRevision:z.number().int().nonnegative(),idempotencyKey:z.string().trim().min(1)}
const managementMutation=z.discriminatedUnion('action',[z.object({action:z.literal('update-settings'),expectedRootRevision:z.number().int().nonnegative(),settings:settingsSchema}).strict(),z.object({action:z.literal('clear-project'),workspaceId:common.workspaceId,projectId:common.projectId,expectedWorkspaceRevision:common.expectedWorkspaceRevision,idempotencyKey:common.idempotencyKey}).strict()])
const mutation=z.discriminatedUnion('action',[z.object({action:z.literal('begin-learning-mode'),sessionId:common.sessionId,activationAttemptId:z.string().trim().min(8).max(128)}).strict(),z.object({action:z.literal('attach-session'),workspaceId:common.workspaceId,sessionId:common.sessionId,expectedWorkspaceRevision:common.expectedWorkspaceRevision,idempotencyKey:common.idempotencyKey}).strict(),z.object({action:z.enum(['start-task','pause-task','resume-task','skip-task','restore-skipped-task','begin-task-check','cancel-task-check']),...common,taskId:z.string().trim().min(1)}).strict(),z.object({action:z.literal('confirm-profile'),...common,profileRevision:z.number().int().positive()}).strict(),z.object({action:z.literal('request-profile-revision'),...common,profileRevision:z.number().int().positive(),reason:z.string().trim().min(1).max(2000)}).strict(),z.object({action:z.literal('approve-plan'),...common,planId:z.string().trim().min(1)}).strict(),z.object({action:z.literal('request-plan-revision'),...common,planId:z.string().trim().min(1),reason:z.string().trim().min(1).max(2000)}).strict()])
async function body(req:IncomingMessage){const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));return JSON.parse(Buffer.concat(chunks).toString()) as unknown}
export interface SessionReader{tailSeq(sessionId:string):number|null}
type WorkspaceResolver=(sessionId:string,claimedWorkspaceId?:string)=>CanonicalWorkspaceContext
export function createLearnLoopHttpHandler(table:StateTable,sessions?:SessionReader,resolveWorkspace?:WorkspaceResolver,onMutation?:(state:LearnLoopState,sessionIds:readonly string[])=>void){return async(req:IncomingMessage,res:ServerResponse)=>{try{
 const url=new URL(req.url??API_PATH,'http://localhost'),state=table.get('singleton')??emptyState()
 const management=(value:LearnLoopState)=>({schemaVersion:11,rootRevision:value.revision,settings:value.settings,workspaces:Object.values(value.workspaces).map(w=>({workspaceId:w.workspaceId,workspaceDisplayName:w.workspaceDisplayName,revision:w.revision,activeProjectId:w.activeProjectId,projects:Object.values(w.projects).map(p=>({id:p.id,title:p.title,phase:p.phase,updatedAt:p.updatedAt}))}))})
 if(req.method==='GET'&&url.pathname===MANAGE_PATH){json(res,200,management(state));return}
 if(req.method==='POST'&&url.pathname===MANAGE_PATH){const parsed=managementMutation.parse(await body(req));const before=table.get('singleton')??emptyState(),oldSession=parsed.action==='clear-project'?before.workspaces[parsed.workspaceId]?.activeSessionId:null,updated=await table.update('singleton',current=>{if(parsed.action==='clear-project')return clearProject(current,parsed);if(current.revision!==parsed.expectedRootRevision)throw new LearnLoopDomainError('REVISION_CONFLICT','Root revision changed.');return{...current,revision:current.revision+1,settings:parsed.settings}});onMutation?.(updated,oldSession?[oldSession]:[]);json(res,200,management(updated));return}
 const workspaceId=url.searchParams.get('workspaceId')?.trim()
 if(req.method==='GET'&&url.pathname===EXPORT_PATH){if(!workspaceId)throw new Error('workspaceId required');const workspace=workspaceOf(state,workspaceId);json(res,200,{backupFormatVersion:6,exportedAt:new Date().toISOString(),pluginVersion:'0.8.0',settings:state.settings,workspace},{'Content-Disposition':`attachment; filename="learnloop-backup-${workspaceId.replace(/[^\w-]/g,'-')}.json"`});return}
 if(req.method==='GET'&&url.pathname===API_PATH){if(!workspaceId)throw new Error('workspaceId required');json(res,200,projectState(state,workspaceId));return}
 if(req.method!=='POST'||url.pathname!==API_PATH)throw new Error('Unsupported LearnLoop route.')
 const parsed=mutation.parse(await body(req));if(!resolveWorkspace)throw new LearnLoopDomainError('WORKSPACE_CONTEXT_MISSING','DSH Workspace resolver is unavailable.');const claimed=parsed.action==='begin-learning-mode'?undefined:parsed.workspaceId,identity=resolveWorkspace(parsed.sessionId,claimed),before=table.get('singleton')??emptyState(),oldSession=before.workspaces[identity.workspaceId]?.activeSessionId;const updated=await table.update('singleton',current=>{if(parsed.action==='begin-learning-mode'){const workspace=current.workspaces[identity.workspaceId];return beginWorkspaceOnboarding(current,{...identity,expectedRevision:workspace?.revision??0,idempotencyKey:`onboarding:${identity.sessionId}:${parsed.activationAttemptId}`})}if(identity.workspaceId!==parsed.workspaceId||identity.sessionId!==parsed.sessionId)throw new LearnLoopDomainError('WORKSPACE_MISMATCH','Claimed Workspace or Session is not canonical.');const canonical:any={...parsed,workspaceId:identity.workspaceId,sessionId:identity.sessionId},expectedRevision=canonical.expectedWorkspaceRevision;if(canonical.action==='attach-session')return attachWorkspaceSession(current,{...canonical,expectedRevision});const input:any={...canonical,expectedRevision};if(canonical.action==='confirm-profile')return confirmWorkspaceProfile(current,input);if(canonical.action==='request-profile-revision')return requestWorkspaceProfileRevision(current,input);if(canonical.action==='approve-plan')return approveWorkspacePlan(current,input);if(canonical.action==='request-plan-revision')return requestWorkspacePlanRevision(current,input);if(canonical.action==='begin-task-check'){const armedAfterSeq=sessions?.tailSeq(canonical.sessionId);if(armedAfterSeq==null)throw new LearnLoopDomainError('SESSION_NOT_LIVE','Session not live.');return beginTaskCheck(current,{...input,armedAfterSeq})}if(canonical.action==='cancel-task-check')return cancelTaskCheck(current,input);if(canonical.action==='start-task')return startTask(current,input);if(canonical.action==='pause-task')return pauseTask(current,input);if(canonical.action==='resume-task')return resumeTask(current,input);if(canonical.action==='skip-task')return skipTask(current,input);return restoreSkippedTask(current,input)});onMutation?.(updated,[...new Set([identity.sessionId,oldSession].filter((id):id is string=>Boolean(id)))]);json(res,200,projectState(updated,identity.workspaceId))
 }catch(error){json(res,error instanceof LearnLoopDomainError?domainStatus(error.code):400,{error:{code:error instanceof LearnLoopDomainError?error.code:'REQUEST_FAILED',message:error instanceof Error?error.message.split('\nLEARNLOOP_SAFE_ERROR:')[0]:'Request failed'}})}}}
