/** LearnLoop Host plugin: durable verified-answer state and same-origin API. */
import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-host-webserver'
import type {} from '@deepseek-ai/dsh-storage-domain'
import type {} from '@deepseek-ai/dsh-tools'
import type {} from '@deepseek-ai/dsh-system-prompt'
import type {} from '@deepseek-ai/dsh-workspace'
import { emptyState, ensureState, learnLoopDomainSpec } from './domain.js'
import { API_PATH, EXPORT_PATH, MANAGE_PATH, createLearnLoopHttpHandler } from './http.js'
import type { StateTable } from './types.js'
import { createLearnLoopApprovePlanTool, createLearnLoopBeginOnboardingTool, createLearnLoopCommitProfileTool, createLearnLoopConfirmProfileTool, createLearnLoopPublishPlanTool } from './tool.js'
import { createLearnLoopAssessmentTool } from './assessment-tool.js'
import { renderLearnLoopSystemSection } from './prompt.js'
import { capturePreStepAnswer, enrichCandidateEvent } from './evidence-bridge.js'
import {resolveCanonicalWorkspace} from './workspace-identity.js'
export * from './workspace-identity.js';export * from './domain.js';export * from './http.js';export * from './types.js';export * from './tool.js';export * from './prompt.js';export * from './assessment-tool.js';export * from './evidence-bridge.js'
export * from './workspace.js'
export const name='learnloop'
export const inject=['storageDomain','webServer','tools','systemPrompt','agents','sessions','workspaceRegistry']
export async function apply(ctx:Context):Promise<void>{const domain=await ctx.storageDomain.open(learnLoopDomainSpec);const table=domain.table('state') as StateTable;await ensureState(table);const workspaceResolver=(sessionId:string,claim?:string)=>resolveCanonicalWorkspace(ctx.workspaceRegistry,sessionId,claim);ctx.effect(()=>ctx.systemPrompt.section({name:'learnloop-runtime',order:50,text:context=>renderLearnLoopSystemSection(table.get('singleton')??emptyState(),context.agent?.id)}),'learnloop.systemPrompt()');ctx.effect(()=>ctx.tools.register(createLearnLoopBeginOnboardingTool(table,workspaceResolver)),'learnloop.beginOnboardingTool()');ctx.effect(()=>ctx.tools.register(createLearnLoopCommitProfileTool(table,workspaceResolver)),'learnloop.commitProfileTool()');ctx.effect(()=>ctx.tools.register(createLearnLoopConfirmProfileTool(table,workspaceResolver)),'learnloop.confirmProfileTool()');ctx.effect(()=>ctx.tools.register(createLearnLoopPublishPlanTool(table,workspaceResolver)),'learnloop.publishPlanTool()');ctx.effect(()=>ctx.tools.register(createLearnLoopApprovePlanTool(table,workspaceResolver)),'learnloop.approvePlanTool()');const sessionReader={tailSeq:(id:string)=>{const session=ctx.sessions.list().find(item=>String(item.id)===id);return session?session.seq:null},requestHeader:(id:string,_callId:string)=>{const session=ctx.sessions.list().find(item=>String(item.id)===id),header=session?.requestHeader();return header?{provider:header.config.provider,model:header.config.model,seq:session!.seq}:null}};ctx.effect(()=>ctx.tools.register(createLearnLoopAssessmentTool(table,sessionReader)),'learnloop.assessmentTool()');ctx.on('agent/pre-step',(payload,next)=>capturePreStepAnswer(table,String(payload.agent.id),payload.signal,next));ctx.on('session/event',(session,sessionEvent)=>{if(sessionEvent.type!=='user/message')return;void table.update('singleton',state=>enrichCandidateEvent(state,String(session.id),sessionEvent.data,sessionEvent.seq))});const handler=createLearnLoopHttpHandler(table,sessionReader,workspaceResolver);ctx.effect(()=>ctx.webServer.register({kind:'exact',path:API_PATH,handler}),'learnloop.stateRoute()');ctx.effect(()=>ctx.webServer.register({kind:'exact',path:EXPORT_PATH,handler}),'learnloop.exportRoute()');ctx.effect(()=>ctx.webServer.register({kind:'exact',path:MANAGE_PATH,handler}),'learnloop.manageRoute()');ctx.effect(()=>async()=>{await domain.close()},'learnloop.storage()')}
