import {defineTool} from '@deepseek-ai/dsh-tools'
import type {Agent} from '@deepseek-ai/dsh-agent'
import {LearnLoopDomainError} from './domain.js'
import {allowedChatReplies,probeDefinition,questionForProbe,type ScaffoldOptionInput} from './interview-probes.js'
import {finalizeLearnLoopToolError} from './tool-protocol.js'
import type {LearnLoopSessionReader} from './dsh-session-adapter.js'
import type {StateTable} from './types.js'
import {activeProject,prepareProfileInterviewQuestion,recordProfileInterviewAnswer,releaseInvalidProfileQuestion,releaseProfileInterviewQuestion,workspaceForSession} from './workspace.js'

interface AskProfileQuestionArgs{questionToken:string;scaffoldOptions?:ScaffoldOptionInput[]}
interface NativeQuestionService{ask(request:{questions:Array<{id:string;question:string;header?:string;options?:Array<{label:string;description?:string}>;multiSelect?:boolean}>;agent?:Agent;signal?:AbortSignal}):Promise<{answers:Array<{id:string;selected:string[];custom?:string}>}>}
export const liveProfileQuestionCalls=new Set<string>()
const releaseReason=(error:unknown)=>{const code=typeof error==='object'&&error!==null&&'code' in error?String(error.code):'';return code==='ASK_ABORTED'?'ask-aborted' as const:code==='CALLER_NOT_LIVE'?'caller-not-live' as const:code==='DELEGATED_CALLER'?'delegated-caller' as const:code==='NO_PROVIDER'?'provider-unavailable' as const:'provider-error' as const}
const levels=['explore','overview','interpret','guided-use','independent-use','design']
export function createLearnLoopProfileQuestionTool(table:StateTable,userQuestions:NativeQuestionService,sessions:LearnLoopSessionReader){return defineTool({name:'learnloop_ask_profile_question',description:'Ask the current Host-owned Profile question using its opaque token. Custom learner text is a supported answer path.',parameters:{questionToken:{type:'string' as const,required:true as const},scaffoldOptions:{type:'array' as const,items:{type:'object' as const,additionalProperties:false,properties:{label:{type:'string' as const,required:true as const},description:{type:'string' as const},level:{type:'string' as const,required:true as const,enum:levels}}}}},output:{schema:{type:'object',additionalProperties:false,properties:{status:{type:'string',required:true,enum:['answered','next-question-ready','scaffolding-required','retry-native-question','fallback-to-chat','wait-for-user','profile-review']},probeId:{type:'string',required:true},nextProbeId:{type:'string'},nextQuestionToken:{type:'string'},prompt:{type:'string'},allowedReplies:{type:'array',items:{type:'string'}}}},render:(_args,value)=>[{type:'text',text:JSON.stringify(value)}]},finalizeContent:finalizeLearnLoopToolError,async execute(rawArgs,exec){const args=rawArgs as unknown as AskProfileQuestionArgs;
 if(!exec.agent)throw new LearnLoopDomainError('WORKSPACE_CONTEXT_MISSING','Tool execution has no DSH Session.')
 const sessionId=String(exec.agent.id),callId=String(exec.callId),workspace=workspaceForSession(table.get('singleton')!,sessionId)
 const prior=table.get('singleton')!.commandReceipts.find(r=>r.workspaceId===workspace.workspaceId&&r.idempotencyKey===`interview:${callId}`)?.result
 if(prior?.kind==='interview-answer-recorded')return{status:prior.status,probeId:prior.probeId,...prior.nextProbeId?{nextProbeId:prior.nextProbeId}:{},...prior.nextQuestionToken?{nextQuestionToken:prior.nextQuestionToken}:{}}
 const released=table.get('singleton')!.commandReceipts.find(r=>r.workspaceId===workspace.workspaceId&&r.idempotencyKey===`interview-release:${callId}`)?.result;if(released?.kind==='interview-question-released')throw new LearnLoopDomainError('INTERVIEW_QUESTION_RELEASED','This Profile question call already reached its released terminal state.')
 const projectBefore=activeProject(workspace),liveKey=`${workspace.workspaceId}:${projectBefore.id}:${callId}`;liveProfileQuestionCalls.add(liveKey)
 try{let current
  try{current=await table.update('singleton',state=>prepareProfileInterviewQuestion(state,{sessionId,callId,questionToken:args.questionToken,scaffoldOptions:args.scaffoldOptions}))}catch(error){if(error instanceof LearnLoopDomainError)throw error;throw new LearnLoopDomainError('INVALID_ARGS','The Profile question request is structurally invalid.')}
  const project=activeProject(workspaceForSession(current,sessionId)),snapshot=project.profileInterview.activeQuestion;if(!snapshot||snapshot.callId!==callId)throw new LearnLoopDomainError('INTERVIEW_QUESTION_STALE','The Profile question token is no longer current.')
  const definition=probeDefinition(snapshot.probeId);let updated
  try{const response=await userQuestions.ask({questions:[{id:snapshot.questionId,question:questionForProbe(snapshot.probeId,project.profileInterview),header:'学习档案',...(snapshot.options.length?{options:snapshot.options.map(o=>({label:o.label,...o.description?{description:o.description}:{}}))}:{}),multiSelect:false}],agent:exec.agent,signal:exec.signal});if(response.answers.length!==1)throw new LearnLoopDomainError('INTERVIEW_QUESTION_CONTRACT_INVALID','Native question service returned an invalid answer count.');const answer=response.answers[0]!,tail=sessions.tailSeq(sessionId);updated=await table.update('singleton',state=>recordProfileInterviewAnswer(state,{sessionId,callId,questionId:answer.id,selected:answer.selected,custom:answer.custom,...tail==null?{}:{fallbackAfterSeq:tail}}))}catch(error){const committed=table.get('singleton')?.commandReceipts.some(r=>r.workspaceId===workspace.workspaceId&&r.idempotencyKey===`interview:${callId}`&&r.result?.kind==='interview-answer-recorded');if(!committed)await table.update('singleton',state=>error instanceof LearnLoopDomainError&&error.code==='INTERVIEW_QUESTION_CONTRACT_INVALID'?releaseInvalidProfileQuestion(state,{sessionId,callId}):releaseProfileInterviewQuestion(state,{sessionId,callId,reason:releaseReason(error)}));throw error}
  const result=updated.commandReceipts.find(r=>r.workspaceId===workspace.workspaceId&&r.idempotencyKey===`interview:${callId}`)?.result;if(!result||result.kind!=='interview-answer-recorded')throw new LearnLoopDomainError('INTERVIEW_QUESTION_CONTRACT_INVALID','Canonical Interview receipt is missing.');const replies=result.status==='fallback-to-chat'?allowedChatReplies(probeDefinition(result.probeId)):[];return{status:result.status,probeId:result.probeId,...result.nextProbeId?{nextProbeId:result.nextProbeId}:{},...result.nextQuestionToken?{nextQuestionToken:result.nextQuestionToken}:{},...(replies.length?{prompt:`请直接回复以下选项之一：\n${replies.map(x=>`- ${x}`).join('\n')}`,allowedReplies:replies}:{})}
 }finally{liveProfileQuestionCalls.delete(liveKey)}}})}
