import type {InterviewProbeId,LearnerProfile,ProfileInterviewState} from './types.js'
import type {GoalIntent} from './interview-probes.js'

const value=(i:ProfileInterviewState,id:InterviewProbeId)=>i.probes[id].normalizedValue
const text=(i:ProfileInterviewState,id:InterviewProbeId)=>String(value(i,id)??'').trim()
const answeredIds=(i:ProfileInterviewState,ids:readonly InterviewProbeId[])=>ids.flatMap(id=>i.probes[id].answerIds).filter(id=>i.answers.some(a=>a.id===id&&(a.status==='answered'||a.status==='uncertain')))
const learnerText=(i:ProfileInterviewState,ids:readonly InterviewProbeId[])=>({kind:'learner-text' as const,answerIds:answeredIds(i,ids)})
export function compileProfileDraftFromInterview(interview:ProfileInterviewState,context:{id:string;revision:number;createdAt:string;updatedAt:string}):LearnerProfile{
 const subject=text(interview,'goal.subject'),outcome=text(interview,'goal.outcome'),deadline=text(interview,'time-budget.deadline'),constraints=text(interview,'constraints.constraints'),examplePreference=text(interview,'learning-mode.example-preference')
 const outcomeAnswer=[...interview.answers].reverse().find(a=>a.probeId==='goal.outcome'&&(a.status==='answered'||a.status==='uncertain'))
 const snapshot=interview.optionSnapshots.find(s=>s.id===interview.activeQuestion?.optionSnapshotId)||[...interview.optionSnapshots].reverse().find(s=>s.probeId==='goal.outcome')
 const option=snapshot?.options.find(o=>outcomeAnswer?.selected.includes(o.label)),recommended=outcomeAnswer?.status==='uncertain'||option?.provenance==='host-uncertainty'
 const goalIntent:GoalIntent=recommended?'overview':option?.level??'overview',desiredOutcome=recommended?'理解核心概念和完整流程':outcome
 const outcomeOrigin=recommended?{kind:'host-recommendation' as const,basedOnAnswerIds:answeredIds(interview,['goal.outcome']),recommendationPolicy:'conservative-entry-overview'}:outcomeAnswer?.custom?learnerText(interview,['goal.outcome']):{kind:'learner-choice' as const,answerIds:answeredIds(interview,['goal.outcome']),optionSnapshotId:snapshot?.id??'missing-snapshot'}
 const highExamples=/(大量案例|案例密集|每个阶段都要有案例|主要通过案例学习)/i.test(examplePreference)
 const fields={goalSubject:learnerText(interview,['goal.subject']),goal:learnerText(interview,['goal.subject']),desiredOutcome:outcomeOrigin,targetOutcome:outcomeOrigin,priorKnowledge:learnerText(interview,['current-foundation.relevant-experience']),experienceLevel:learnerText(interview,['current-foundation.level']),knowledgeGaps:learnerText(interview,['knowledge-gaps.primary-gaps']),weeklyHours:learnerText(interview,['time-budget.weekly-hours']),deadline:learnerText(interview,['time-budget.deadline']),learningMode:learnerText(interview,['learning-mode.mode']),practiceCapacity:learnerText(interview,['practice-capacity.capacity']),constraints:learnerText(interview,['constraints.constraints']),successCriteria:learnerText(interview,['success-criteria.criteria']),explanationDepth:{kind:'host-default' as const,defaultName:'standard'},exampleDensity:examplePreference?learnerText(interview,['learning-mode.example-preference']):{kind:'host-default' as const,defaultName:'standard'},additionalNotes:examplePreference?learnerText(interview,['learning-mode.example-preference']):{kind:'host-default' as const,defaultName:'empty'}}
 return{id:context.id,revision:context.revision,goal:`${subject}，并${desiredOutcome}`,goalSubject:subject,goalIntent,desiredOutcome,goalKind:null,targetOutcome:[desiredOutcome,text(interview,'target-outcome.quality-bar')].filter(Boolean).join(' / '),priorKnowledge:text(interview,'current-foundation.relevant-experience'),experienceLevel:(value(interview,'current-foundation.level')||'beginner') as LearnerProfile['experienceLevel'],knowledgeGaps:[text(interview,'knowledge-gaps.primary-gaps')],learningPreferences:{mode:(value(interview,'learning-mode.mode')||'balanced') as LearnerProfile['learningPreferences']['mode'],practiceCapacity:(value(interview,'practice-capacity.capacity')||'none') as LearnerProfile['learningPreferences']['practiceCapacity'],explanationDepth:'standard',exampleDensity:highExamples?'high':'standard',additionalNotes:examplePreference},weeklyHours:Number(value(interview,'time-budget.weekly-hours')||10),deadline:deadline&&!['无','没有','不知道','none','no deadline'].includes(deadline.toLowerCase())?deadline:undefined,constraints:['无','没有','无额外限制','none'].includes(constraints.toLowerCase())?[]:[constraints].filter(Boolean),successCriteria:[text(interview,'success-criteria.criteria')||desiredOutcome],unansweredQuestions:[],fieldOrigins:fields,confirmedAt:null,createdAt:context.createdAt,updatedAt:context.updatedAt}
}
