import type {LearnerProfile,ProfileInterviewState} from './types.js'

const value=(interview:ProfileInterviewState,id:keyof ProfileInterviewState['probes'])=>interview.probes[id].normalizedValue
const text=(interview:ProfileInterviewState,id:keyof ProfileInterviewState['probes'])=>String(value(interview,id)??'').trim()
const evidence=(interview:ProfileInterviewState,id:keyof ProfileInterviewState['probes'])=>({kind:'learner-evidence' as const,topic:interview.probes[id].topic,answerIds:interview.probes[id].answerIds})
export function compileProfileDraftFromInterview(interview:ProfileInterviewState,context:{id:string;revision:number;createdAt:string;updatedAt:string}):LearnerProfile{
 const kind=text(interview,'goal.kind'),subject=text(interview,'goal.subject'),deadline=text(interview,'time-budget.deadline'),constraints=text(interview,'constraints.constraints')
 const fields={goal:evidence(interview,'goal.subject'),targetOutcome:evidence(interview,'target-outcome.capability'),priorKnowledge:evidence(interview,'current-foundation.relevant-experience'),experienceLevel:evidence(interview,'current-foundation.level'),knowledgeGaps:evidence(interview,'knowledge-gaps.primary-gaps'),weeklyHours:evidence(interview,'time-budget.weekly-hours'),deadline:evidence(interview,'time-budget.deadline'),learningMode:evidence(interview,'learning-mode.mode'),practiceCapacity:evidence(interview,'practice-capacity.capacity'),constraints:evidence(interview,'constraints.constraints'),successCriteria:evidence(interview,'success-criteria.criteria'),explanationDepth:{kind:'host-default' as const,defaultName:'standard'},exampleDensity:{kind:'host-default' as const,defaultName:'standard'},additionalNotes:{kind:'host-default' as const,defaultName:'empty'}}
 return{id:context.id,revision:context.revision,goal:`${kind}: ${subject}`,targetOutcome:[text(interview,'target-outcome.capability'),text(interview,'target-outcome.quality-bar')].filter(Boolean).join(' / '),priorKnowledge:text(interview,'current-foundation.relevant-experience'),experienceLevel:value(interview,'current-foundation.level') as LearnerProfile['experienceLevel'],knowledgeGaps:[text(interview,'knowledge-gaps.primary-gaps')],learningPreferences:{mode:value(interview,'learning-mode.mode') as LearnerProfile['learningPreferences']['mode'],practiceCapacity:value(interview,'practice-capacity.capacity') as LearnerProfile['learningPreferences']['practiceCapacity'],explanationDepth:'standard',exampleDensity:'standard',additionalNotes:''},weeklyHours:Number(value(interview,'time-budget.weekly-hours')),deadline:deadline&&!['无','none','no deadline'].includes(deadline.toLowerCase())?deadline:undefined,constraints:['无','没有','无额外限制','none'].includes(constraints.toLowerCase())?[]:[constraints],successCriteria:[text(interview,'success-criteria.criteria')],unansweredQuestions:[],fieldOrigins:fields,confirmedAt:null,createdAt:context.createdAt,updatedAt:context.updatedAt}
}
