import type {InterviewProbeId,LearnerProfile,ProfileInterviewState} from './types.js'
import {probeDefinition} from './interview-probes.js'

const value=(interview:ProfileInterviewState,id:InterviewProbeId)=>interview.probes[id].normalizedValue
const text=(interview:ProfileInterviewState,id:InterviewProbeId)=>String(value(interview,id)??'').trim()
const evidence=(interview:ProfileInterviewState,ids:readonly InterviewProbeId[])=>({kind:'learner-evidence' as const,topic:interview.probes[ids[0]!].topic,answerIds:ids.flatMap(id=>interview.probes[id].answerIds).filter(id=>interview.answers.some(answer=>answer.id===id&&answer.status==='answered'))})

export function compileProfileDraftFromInterview(interview:ProfileInterviewState,context:{id:string;revision:number;createdAt:string;updatedAt:string}):LearnerProfile{
 const kind=text(interview,'goal.kind'),subject=text(interview,'goal.subject'),deadline=text(interview,'time-budget.deadline'),constraints=text(interview,'constraints.constraints'),examplePreference=text(interview,'learning-mode.example-preference')
 const highExamples=/(大量案例|案例密集|每个阶段都要有案例|每个知识点都需要示例|每个知识点都要有(?:大量)?案例|主要通过案例学习)/i.test(examplePreference)
 const kindLabel=probeDefinition('goal.kind').options?.find(option=>option.value===kind)?.label??kind
 const goalPrefix:Record<string,string>={skill:'掌握技能',project:'完成项目',exam:'通过认证',domain:'系统学习领域'}
 const fields={
  goal:evidence(interview,['goal.kind','goal.subject']),targetOutcome:evidence(interview,['target-outcome.capability','target-outcome.quality-bar']),priorKnowledge:evidence(interview,['current-foundation.relevant-experience']),experienceLevel:evidence(interview,['current-foundation.level']),knowledgeGaps:evidence(interview,['knowledge-gaps.primary-gaps']),weeklyHours:evidence(interview,['time-budget.weekly-hours']),deadline:evidence(interview,['time-budget.deadline']),learningMode:evidence(interview,['learning-mode.mode']),practiceCapacity:evidence(interview,['practice-capacity.capacity']),constraints:evidence(interview,['constraints.constraints']),successCriteria:evidence(interview,['success-criteria.criteria']),explanationDepth:{kind:'host-default' as const,defaultName:'standard'},exampleDensity:examplePreference?evidence(interview,['learning-mode.example-preference']):{kind:'host-default' as const,defaultName:'standard'},additionalNotes:examplePreference?evidence(interview,['learning-mode.example-preference']):{kind:'host-default' as const,defaultName:'empty'}
 }
 return{id:context.id,revision:context.revision,goal:`${goalPrefix[kind]??kindLabel}：${subject}`,targetOutcome:[text(interview,'target-outcome.capability'),text(interview,'target-outcome.quality-bar')].filter(Boolean).join(' / '),priorKnowledge:text(interview,'current-foundation.relevant-experience'),experienceLevel:value(interview,'current-foundation.level') as LearnerProfile['experienceLevel'],knowledgeGaps:[text(interview,'knowledge-gaps.primary-gaps')],learningPreferences:{mode:value(interview,'learning-mode.mode') as LearnerProfile['learningPreferences']['mode'],practiceCapacity:value(interview,'practice-capacity.capacity') as LearnerProfile['learningPreferences']['practiceCapacity'],explanationDepth:'standard',exampleDensity:highExamples?'high':'standard',additionalNotes:examplePreference},weeklyHours:Number(value(interview,'time-budget.weekly-hours')),deadline:deadline&&!['无','none','no deadline'].includes(deadline.toLowerCase())?deadline:undefined,constraints:['无','没有','无额外限制','none'].includes(constraints.toLowerCase())?[]:[constraints],successCriteria:[text(interview,'success-criteria.criteria')],unansweredQuestions:[],fieldOrigins:fields,confirmedAt:null,createdAt:context.createdAt,updatedAt:context.updatedAt}
}
