import { defineTool } from '@deepseek-ai/dsh-tools'
import { LearnLoopDomainError } from './domain.js'
import { activeProject, approveWorkspacePlan, beginWorkspaceOnboarding, commitWorkspaceProfile, confirmWorkspaceProfile, publishWorkspacePlanDraft } from './workspace.js'
import type { GeneratedPlanInput, StateTable } from './types.js'
import type {CanonicalWorkspaceContext} from './workspace-identity.js'
type WorkspaceResolver=(sessionId:string,claimedWorkspaceId?:string)=>CanonicalWorkspaceContext
const canonical=(exec:{agent?:{id:unknown}},resolver:WorkspaceResolver,claim:string)=>{if(!exec.agent)throw new LearnLoopDomainError('WORKSPACE_CONTEXT_MISSING','Tool execution has no DSH Session.');return resolver(String(exec.agent.id),claim)}
const stringItem={type:'string' as const}
const text={...stringItem,required:true as const}, integer={type:'integer' as const,required:true as const}
const key={...text,description:'Stable lowercase key; never a database id.'}
const workspaceRevision={...integer,description:'Current workspace revision from GET /learnloop/api/v2/state at workspace.revision; this is not the top-level state revision.'}
const workspaceClaim={...text,description:'Compatibility declaration only. The Host derives the canonical UUID from the current Session and rejects a mismatch.'}
export function createLearnLoopBeginOnboardingTool(table:StateTable,resolveWorkspace:WorkspaceResolver){return defineTool({name:'learnloop_begin_onboarding',description:'Begin an explicitly requested guided interview in the current Session DSH Workspace; the Host validates its canonical UUID. Ask one native user question after this command.',parameters:{workspaceId:workspaceClaim,expectedRevision:workspaceRevision,idempotencyKey:text},output:{schema:{type:'object',additionalProperties:false,properties:{status:{type:'string',const:'interviewing',required:true},projectId:text,revision:integer}},render:(_a,v)=>[{type:'text',text:`Interview started (projectId=${v.projectId}, revision=${v.revision}). Ask exactly one core question with ask_user_question.`}]},async execute(args,exec){const identity=canonical(exec,resolveWorkspace,args.workspaceId);const updated=await table.update('singleton',state=>beginWorkspaceOnboarding(state,{...args,...identity}));const workspace=updated.workspaces[identity.workspaceId]!;return{status:'interviewing' as const,projectId:workspace.activeProjectId!,revision:workspace.revision}}})}
export function createLearnLoopCommitProfileTool(table:StateTable,resolveWorkspace:WorkspaceResolver){return defineTool({name:'learnloop_commit_profile',description:'Commit only learner-supported structured profile facts to the current stable workspace. This creates no active plan.',parameters:{workspaceId:text,projectId:text,expectedRevision:workspaceRevision,idempotencyKey:text,goal:text,priorKnowledge:text,experienceLevel:{type:'string',required:true,enum:['beginner','intermediate','advanced']},knowledgeGaps:{type:'array',required:true,items:stringItem},learningMode:{type:'string',required:true,enum:['knowledge-first','balanced','practice-first']},practiceCapacity:{type:'string',required:true,enum:['none','light','full']},weeklyHours:integer,deadline:{type:'string'},constraints:{type:'array',required:true,items:stringItem},successCriteria:{type:'array',required:true,items:stringItem},unansweredQuestions:{type:'array',required:true,items:stringItem}},output:{schema:{type:'object',additionalProperties:false,properties:{status:{type:'string',const:'profile-review',required:true},revision:integer,profileRevision:integer}},render:(_a,v)=>[{type:'text',text:`Profile revision ${v.profileRevision} is awaiting explicit learner confirmation (revision=${v.revision}).`}]},async execute(args,exec){const identity=canonical(exec,resolveWorkspace,args.workspaceId);const updated=await table.update('singleton',state=>commitWorkspaceProfile(state,{...args,workspaceId:identity.workspaceId}));const workspace=updated.workspaces[identity.workspaceId]!;return{status:'profile-review' as const,revision:workspace.revision,profileRevision:activeProject(workspace).profileRevision}}})}
export function createLearnLoopConfirmProfileTool(table:StateTable,resolveWorkspace:WorkspaceResolver){return defineTool({name:'learnloop_confirm_profile',description:'Confirm the current profile revision only after the learner explicitly approved the displayed profile in the native question dialog.',parameters:{workspaceId:text,projectId:text,profileRevision:integer,expectedRevision:workspaceRevision,idempotencyKey:text},output:{schema:{type:'object',additionalProperties:false,properties:{status:{type:'string',const:'planning',required:true},revision:integer,profileRevision:integer}},render:(_a,v)=>[{type:'text',text:`Profile revision ${v.profileRevision} is confirmed (revision=${v.revision}). Generate and publish the plan draft next.`}]},async execute(args,exec){const identity=canonical(exec,resolveWorkspace,args.workspaceId);const updated=await table.update('singleton',state=>confirmWorkspaceProfile(state,{...args,workspaceId:identity.workspaceId}));const workspace=updated.workspaces[identity.workspaceId]!;return{status:'planning' as const,revision:workspace.revision,profileRevision:activeProject(workspace).profileRevision}}})}
export function createLearnLoopPublishPlanTool(table:StateTable,resolveWorkspace:WorkspaceResolver){
  const task={type:'object' as const,additionalProperties:false,properties:{key,title:text,objective:text,acceptanceCriteria:{type:'array' as const,required:true as const,items:stringItem},estimateMinutes:integer,conceptKey:key,conceptTitle:text,dependsOn:{type:'array' as const,required:true as const,items:stringItem},kind:{type:'string' as const,required:true as const,enum:['lesson','worked-example','discussion','exercise','implementation']},completion:{type:'object' as const,required:true as const,additionalProperties:false,properties:{kind:{type:'string' as const,required:true as const,enum:['short-answer','reflection','artifact']},prompt:text}}}}
  const stage={type:'object' as const,additionalProperties:false,properties:{key,title:text,tasks:{type:'array' as const,required:true as const,items:task}}}
  return defineTool({name:'learnloop_publish_plan',description:'Publish a complete draft plan for an explicitly confirmed workspace profile. Host validates ownership, revisions, dependencies, DAG, bounds, and practice capacity. The learner must approve it separately.',parameters:{workspaceId:text,projectId:text,profileRevision:integer,expectedRevision:workspaceRevision,idempotencyKey:text,stages:{type:'array',required:true,items:stage}},output:{schema:{type:'object',additionalProperties:false,properties:{status:{type:'string',const:'draft',required:true},revision:integer,planId:text,planVersion:integer}},render:(_a,v)=>[{type:'text',text:`Plan draft ${v.planVersion} (planId=${v.planId}, revision=${v.revision}) awaits explicit learner approval; do not start teaching.`}]},async execute(args,exec){const identity=canonical(exec,resolveWorkspace,args.workspaceId);const updated=await table.update('singleton',state=>publishWorkspacePlanDraft(state,{...args,workspaceId:identity.workspaceId,stages:args.stages as GeneratedPlanInput['stages']}));const workspace=updated.workspaces[identity.workspaceId]!,plan=activeProject(workspace).plans.at(-1)!;return{status:'draft' as const,revision:workspace.revision,planId:plan.id,planVersion:plan.version}}})
}
export function createLearnLoopApprovePlanTool(table:StateTable,resolveWorkspace:WorkspaceResolver){return defineTool({name:'learnloop_approve_plan',description:'Activate a draft only after the learner explicitly selected approve in the native question dialog.',parameters:{workspaceId:text,projectId:text,planId:text,expectedRevision:workspaceRevision,idempotencyKey:text},output:{schema:{type:'object',additionalProperties:false,properties:{status:{type:'string',const:'active',required:true},revision:integer}},render:(_a,v)=>[{type:'text',text:`The approved plan is active (revision=${v.revision}).`}]},async execute(args,exec){const identity=canonical(exec,resolveWorkspace,args.workspaceId);const updated=await table.update('singleton',state=>approveWorkspacePlan(state,{...args,workspaceId:identity.workspaceId,sessionId:identity.sessionId}));return{status:'active' as const,revision:updated.workspaces[identity.workspaceId]!.revision}}})}
