import {randomUUID} from 'node:crypto'
import {DEFAULT_PREFERENCES, LearnLoopDomainError, payloadHash} from './domain.js'
import {learnLoopStateSchema, type Assessment, type CriterionAssessment, type GeneratedPlanInput, type LearnerProfile, type LearningProject, type LearningTask, type LearnLoopState, type VerifiedTaskAssessment, type WorkspaceLearningState} from './types.js'

const now=()=>new Date().toISOString(); const uid=(p:string)=>`${p}_${randomUUID()}`
const fail=(code:ConstructorParameters<typeof LearnLoopDomainError>[0],message:string):never=>{throw new LearnLoopDomainError(code,message)}
export function emptyWorkspace(workspaceId:string):WorkspaceLearningState{return{workspaceId,revision:0,activeProjectId:null,projects:{},activeSessionId:null,events:[]}}
export function workspaceOf(state:LearnLoopState,workspaceId:string){const id=workspaceId.trim();if(!id)fail('PROJECT_NOT_FOUND','A stable workspaceId is required.');return state.workspaces[id]??emptyWorkspace(id)}
export function workspaceForSession(state:LearnLoopState,sessionId:string){const matches=Object.values(state.workspaces).filter(w=>w.activeSessionId===sessionId.trim());if(!matches.length)fail('PROJECT_NOT_FOUND','No workspace is attached to this session.');if(matches.length!==1)fail('WORKSPACE_AMBIGUOUS','Session is active in multiple LearnLoop Workspaces.');return matches[0]!}
export function activeProject(workspace:WorkspaceLearningState){const project=workspace.activeProjectId?workspace.projects[workspace.activeProjectId]:undefined;if(!project)fail('PROJECT_NOT_FOUND','Active project not found.');return project}
type Context={workspaceId:string;projectId:string|null;sessionId?:string;expectedRevision:number;idempotencyKey:string}
export function applyWorkspaceCommand(state:LearnLoopState,context:Context,action:string,payload:unknown,mutation:(workspace:WorkspaceLearningState,project:LearningProject|null)=>WorkspaceLearningState){
 const fingerprint=payloadHash({action,workspaceId:context.workspaceId,projectId:context.projectId,payload});const prior=state.commandReceipts.find(r=>r.workspaceId===context.workspaceId&&r.idempotencyKey===context.idempotencyKey)
 if(prior){if(prior.action===action&&prior.payloadHash===fingerprint)return state;fail('IDEMPOTENCY_KEY_REUSED','Idempotency key was reused with different content.')}
 const workspace=workspaceOf(state,context.workspaceId);if(workspace.revision!==context.expectedRevision)fail('REVISION_CONFLICT','Workspace revision changed.')
 const project=context.projectId?workspace.projects[context.projectId]:null;if(context.projectId&&!project)fail('PROJECT_NOT_FOUND','Project is not in this workspace.');if(project&&workspace.activeProjectId!==project.id)fail('PROJECT_NOT_FOUND','Project is not active.')
 if(context.sessionId&&workspace.activeSessionId!==context.sessionId)fail('SESSION_MISMATCH','Session is not attached to this workspace.')
 const changed=mutation(structuredClone(workspace),project?structuredClone(project):null);const stamp=now();const nextWorkspace={...changed,revision:workspace.revision+1,events:[...changed.events,{id:uid('event'),stableId:context.idempotencyKey,type:action,summary:action,createdAt:stamp}]};const revision=state.revision+1
 return learnLoopStateSchema.parse({...state,revision,workspaces:{...state.workspaces,[workspace.workspaceId]:nextWorkspace},commandReceipts:[...state.commandReceipts,{idempotencyKey:context.idempotencyKey,action,workspaceId:workspace.workspaceId,projectId:context.projectId,payloadHash:fingerprint,resultRevision:revision,createdAt:stamp}]})
}
export function beginWorkspaceOnboarding(state:LearnLoopState,input:{workspaceId:string;expectedRevision:number;idempotencyKey:string;sessionId:string;workspaceRootSnapshot?:string;workspaceDisplayName?:string}){return applyWorkspaceCommand(state,{workspaceId:input.workspaceId,projectId:null,expectedRevision:input.expectedRevision,idempotencyKey:input.idempotencyKey},'workspace:onboarding',input,(workspace)=>{if(Object.values(workspace.projects).some(p=>p.phase!=='archived'))fail('PROJECT_ALREADY_EXISTS','Workspace already has a current project.');const at=now(),project:LearningProject={id:uid('project'),title:'学习项目',phase:'interviewing',profile:null,profileRevision:0,plans:[],activePlanId:null,evidence:[],mastery:[],assessments:[],adjustments:[],evidenceCandidates:[],misconceptions:[],reviewQueue:[],execution:null,createdAt:at,updatedAt:at};return{...workspace,workspaceRootSnapshot:input.workspaceRootSnapshot,workspaceDisplayName:input.workspaceDisplayName,projects:{...workspace.projects,[project.id]:project},activeProjectId:project.id,activeSessionId:input.sessionId}})}
export function attachWorkspaceSession(state:LearnLoopState,input:{workspaceId:string;expectedRevision:number;idempotencyKey:string;sessionId:string}){const workspace=workspaceOf(state,input.workspaceId);return applyWorkspaceCommand(state,{workspaceId:input.workspaceId,projectId:workspace.activeProjectId,expectedRevision:input.expectedRevision,idempotencyKey:input.idempotencyKey},'workspace:attach-session',input,w=>({...w,activeSessionId:input.sessionId}))}
export interface CommitProfileInput{workspaceId:string;projectId:string;expectedRevision:number;idempotencyKey:string;goal:string;priorKnowledge:string;experienceLevel:'beginner'|'intermediate'|'advanced';knowledgeGaps:string[];learningMode:'knowledge-first'|'balanced'|'practice-first';practiceCapacity:'none'|'light'|'full';weeklyHours:number;deadline?:string;constraints:string[];successCriteria:string[];unansweredQuestions:string[]}
export function commitWorkspaceProfile(state:LearnLoopState,input:CommitProfileInput){return applyWorkspaceCommand(state,{...input,sessionId:undefined},'workspace:commit-profile',input,(w,p)=>{if(!p)fail('PROJECT_NOT_FOUND','Project missing.');const at=now(),rev=p.profileRevision+1;const profile:LearnerProfile={id:p.profile?.id??uid('profile'),revision:rev,goal:input.goal.trim(),priorKnowledge:input.priorKnowledge.trim(),experienceLevel:input.experienceLevel,knowledgeGaps:input.knowledgeGaps,learningPreferences:{...DEFAULT_PREFERENCES,mode:input.learningMode,practiceCapacity:input.practiceCapacity},weeklyHours:input.weeklyHours,deadline:input.deadline,constraints:input.constraints,successCriteria:input.successCriteria,unansweredQuestions:input.unansweredQuestions,confirmedAt:null,createdAt:p.profile?.createdAt??at,updatedAt:at};const project={...p,title:profile.goal.slice(0,40),profile,profileRevision:rev,phase:'profile_review' as const,updatedAt:at};return{...w,projects:{...w.projects,[p.id]:project}}})}
export function confirmWorkspaceProfile(state:LearnLoopState,input:{workspaceId:string;projectId:string;expectedRevision:number;profileRevision:number;idempotencyKey:string}){return applyWorkspaceCommand(state,input,'workspace:confirm-profile',input,(w,p)=>{if(!p?.profile||p.profileRevision!==input.profileRevision)fail('REVISION_CONFLICT','Profile revision changed.');const at=now(),project={...p,phase:'planning' as const,profile:{...p.profile,confirmedAt:at,updatedAt:at},updatedAt:at};return{...w,projects:{...w.projects,[p.id]:project}}})}
export function validateGeneratedPlan(input:GeneratedPlanInput,capacity:'none'|'light'|'full'){if(input.stages.length<1||input.stages.length>8)fail('INVALID_PLAN','Plan must contain 1 to 8 stages.');const keys=new Set(input.stages.flatMap(s=>s.tasks.map(t=>t.key)));if(keys.size!==input.stages.flatMap(s=>s.tasks).length)fail('INVALID_PLAN','Task keys must be unique.');for(const task of input.stages.flatMap(s=>s.tasks)){if(!task.acceptanceCriteria.length||task.dependsOn.some(d=>!keys.has(d)||d===task.key))fail('INVALID_PLAN','Task criteria or dependency is invalid.');if(capacity==='none'&&['exercise','implementation'].includes(task.kind))fail('INVALID_PLAN','Plan conflicts with practice capacity.')}}
export function publishWorkspacePlanDraft(state:LearnLoopState,input:GeneratedPlanInput&{workspaceId:string;projectId:string;profileRevision:number;expectedRevision:number;idempotencyKey:string}){validateGeneratedPlan(input,activeProject(workspaceOf(state,input.workspaceId)).profile?.learningPreferences.practiceCapacity??'light');return applyWorkspaceCommand(state,input,'workspace:publish-plan-draft',input,(w,p)=>{if(!p?.profile?.confirmedAt||p.profileRevision!==input.profileRevision)fail('REVISION_CONFLICT','Confirmed profile changed.');const at=now(),stages=input.stages.map(s=>({id:`stage-${s.key}`,title:s.title,tasks:s.tasks.map(t=>({id:`task-${t.key}`,title:t.title,objective:t.objective,acceptanceCriteria:t.acceptanceCriteria,estimateMinutes:t.estimateMinutes,status:'pending' as const,conceptIds:[`concept-${t.conceptKey}`],dependsOn:t.dependsOn.map(d=>`concept-${d}`),kind:t.kind,completion:t.completion}))})),plan={id:uid('plan'),version:Math.max(0,...p.plans.map(x=>x.version))+1,status:'draft' as const,createdAt:at,stages};const project={...p,plans:[...p.plans,plan],phase:'plan_review' as const,updatedAt:at};return{...w,projects:{...w.projects,[p.id]:project}}})}
export function approveWorkspacePlan(state:LearnLoopState,input:{workspaceId:string;projectId:string;planId:string;expectedRevision:number;idempotencyKey:string;sessionId:string}){return applyWorkspaceCommand(state,{...input,sessionId:undefined},'workspace:approve-plan',input,(w,p)=>{if(!p)fail('PROJECT_NOT_FOUND','Project missing.');const draft=p.plans.find(x=>x.id===input.planId&&x.status==='draft');if(!draft)fail('PLAN_NOT_PUBLISHED','Draft plan not found.');const at=now(),plans=p.plans.map(x=>x.id===draft.id?{...x,status:'active' as const,stages:x.stages.map((s,si)=>({...s,tasks:s.tasks.map((t,ti)=>({...t,status:si===0&&ti===0?'active' as const:t.status}))}))}:x.status==='active'?{...x,status:'superseded' as const}:x);const first=plans.find(x=>x.id===draft.id)!.stages[0]!.tasks[0]!;const project={...p,plans,activePlanId:draft.id,phase:'active' as const,mastery:plans.find(x=>x.id===draft.id)!.stages.flatMap(s=>s.tasks).map(t=>({conceptId:t.conceptIds[0]!,title:t.title,level:'introduced' as const,evidenceIds:[],rationale:'Introduced by the approved plan.',updatedAt:at})),execution:{taskId:first.id,phase:'teaching' as const,attempt:0,armedAfterSeq:null,candidateId:null,lastAssessmentId:null,updatedAt:at},updatedAt:at};return{...w,activeSessionId:input.sessionId,projects:{...w.projects,[p.id]:project}}})}
function mutateTask(state:LearnLoopState,input:{workspaceId:string;projectId:string;sessionId:string;taskId:string;expectedRevision:number;idempotencyKey:string},action:string,fn:(task:LearningTask,p:LearningProject)=>LearningTask){return applyWorkspaceCommand(state,input,action,input,(w,p)=>{if(!p)fail('PROJECT_NOT_FOUND','Project missing.');const plan=p.plans.find(x=>x.id===p.activePlanId);if(!plan)fail('PLAN_NOT_PUBLISHED','Active plan missing.');let found=false;const plans=p.plans.map(x=>x.id===plan.id?{...x,stages:x.stages.map(s=>({...s,tasks:s.tasks.map(t=>{if(t.id!==input.taskId)return t;found=true;return fn(t,p)})}))}:x);if(!found)fail('TASK_NOT_FOUND','Task missing.');return{...w,projects:{...w.projects,[p.id]:{...p,plans,updatedAt:now()}}}})}
export const startTask=(s:LearnLoopState,i:Parameters<typeof mutateTask>[1])=>mutateTask(s,i,'task:start',(t)=>({...t,status:'active'}));export const pauseTask=(s:LearnLoopState,i:Parameters<typeof mutateTask>[1])=>mutateTask(s,i,'task:pause',(t)=>({...t,status:'blocked'}));export const resumeTask=(s:LearnLoopState,i:Parameters<typeof mutateTask>[1])=>mutateTask(s,i,'task:resume',(t)=>({...t,status:'active'}));export const skipTask=(s:LearnLoopState,i:Parameters<typeof mutateTask>[1])=>mutateTask(s,i,'task:skip',(t)=>({...t,status:'skipped'}));export const restoreSkippedTask=(s:LearnLoopState,i:Parameters<typeof mutateTask>[1])=>mutateTask(s,i,'task:restore',(t)=>({...t,status:'pending'}))
export function beginTaskCheck(state:LearnLoopState,input:Parameters<typeof mutateTask>[1]&{armedAfterSeq:number}){return applyWorkspaceCommand(state,input,'task:begin-check',input,(w,p)=>{if(!p?.execution||p.execution.taskId!==input.taskId)fail('TASK_NOT_FOUND','Current task missing.');const project={...p,execution:{...p.execution,phase:'awaiting-answer' as const,armedAfterSeq:input.armedAfterSeq,candidateId:null,updatedAt:now()}};return{...w,projects:{...w.projects,[p.id]:project}}})}
export function createEvidenceCandidate(state:LearnLoopState,input:{sessionId:string;messageIds:string[];answerText:string;contentHash:string;eventSeqs:number[]}){const w=workspaceForSession(state,input.sessionId),p=activeProject(w);if(p.execution?.phase!=='awaiting-answer')fail('CHECK_NOT_ARMED','Check is not awaiting an answer.');return applyWorkspaceCommand(state,{workspaceId:w.workspaceId,projectId:p.id,sessionId:input.sessionId,expectedRevision:w.revision,idempotencyKey:`candidate:${input.contentHash}`},'evidence:candidate',input,(ws,project)=>{const at=now(),candidate={id:uid('candidate'),taskId:project!.execution!.taskId,conceptId:project!.plans.find(x=>x.id===project!.activePlanId)!.stages.flatMap(s=>s.tasks).find(t=>t.id===project!.execution!.taskId)!.conceptIds[0]!,source:{sessionId:input.sessionId,messageIds:input.messageIds,eventSeqs:input.eventSeqs,contentHash:input.contentHash},answerText:input.answerText,status:'pending-verification' as const,attempt:project!.execution!.attempt+1,assessmentId:null,createdAt:at,updatedAt:at};const changed={...project!,evidenceCandidates:[...project!.evidenceCandidates,candidate],execution:{...project!.execution!,phase:'verifying' as const,attempt:candidate.attempt,candidateId:candidate.id,updatedAt:at}};return{...ws,projects:{...ws.projects,[changed.id]:changed}}})}
export function assessCurrentCandidate(state:LearnLoopState,input:{sessionId:string;idempotencyKey:string;criteria:CriterionAssessment[];overall:'needs-work'|'passed'|'excellent';misconceptions:string[];feedback:string;verifier:VerifiedTaskAssessment['verifier']}){const w=workspaceForSession(state,input.sessionId),p=activeProject(w),candidate=p.evidenceCandidates.find(c=>c.id===p.execution?.candidateId);if(!candidate)fail('CANDIDATE_NOT_FOUND','Candidate missing.');return applyWorkspaceCommand(state,{workspaceId:w.workspaceId,projectId:p.id,sessionId:input.sessionId,expectedRevision:w.revision,idempotencyKey:input.idempotencyKey},'evidence:assess',input,(ws,project)=>{const at=now(),assessment:Assessment={kind:'verified-task',id:uid('assessment'),candidateId:candidate.id,taskId:candidate.taskId,conceptId:candidate.conceptId,result:input.overall,criteria:input.criteria,misconceptions:input.misconceptions,feedback:input.feedback,verifier:input.verifier,createdAt:at};let changed={...project!,assessments:[...project!.assessments,assessment],evidenceCandidates:project!.evidenceCandidates.map(c=>c.id===candidate.id?{...c,status:input.overall==='needs-work'?'needs-work' as const:'accepted' as const,assessmentId:assessment.id,updatedAt:at}:c),misconceptions:[...new Set([...project!.misconceptions,...input.misconceptions])],execution:{...project!.execution!,phase:input.overall==='needs-work'?'needs-revision' as const:'passed' as const,lastAssessmentId:assessment.id,updatedAt:at}};if(input.overall!=='needs-work'){const evidence={provenance:'verified' as const,id:uid('evidence'),idempotencyKey:input.idempotencyKey,conceptId:candidate.conceptId,kind:'assessment' as const,summary:input.feedback,assessmentId:assessment.id,source:{kind:'dsh-message' as const,...candidate.source},createdAt:at};changed={...changed,evidence:[...changed.evidence,evidence],mastery:changed.mastery.map(m=>m.conceptId===candidate.conceptId?{...m,level:input.overall==='excellent'?'mastered' as const:'demonstrated' as const,evidenceIds:[...m.evidenceIds,evidence.id],rationale:input.feedback,updatedAt:at}:m),plans:changed.plans.map(plan=>plan.id===changed.activePlanId?{...plan,stages:plan.stages.map(s=>({...s,tasks:s.tasks.map(t=>t.id===candidate.taskId?{...t,status:'completed' as const}:t)}))}:plan)}}return{...ws,projects:{...ws.projects,[changed.id]:changed}}})}
export function nextAction(project:LearningProject){const plan=project.plans.find(p=>p.id===project.activePlanId);return plan?.stages.flatMap(s=>s.tasks).find(t=>['active','blocked','pending'].includes(t.status))??null}
